polish(jrn): polish mbpo doc
opendilab/DI-engine-docs pull request #111
Opened 2022-03-30 10:06 UTC by jiaruonan

2022-03-30 10:49 UTC, PaParaZz1 requested changes

2022-03-30 10:49 UTC, PaParaZz1 commented on source/hands_on/mbpo.rst
>  1. The above results are obtained by running the same configuration on five different random seeds (0, 1, 2, 3, 4)
3seed

2022-03-30 10:49 UTC, PaParaZz1 commented on source/hands_on/mbpo.rst
> +For the choice of RL policy, MBPO use SAC as its RL component.
add a link to `awesome` repo

2022-03-30 10:49 UTC, PaParaZz1 commented on source/hands_on/mbpo.rst
> +
talk something about `a guarantee of monotonic improvement`

2022-03-30 16:36 UTC, jiaruonan commented on source/hands_on/mbpo.rst
>  1. The above results are obtained by running the same configuration on five different random seeds (0, 1, 2, 3, 4)
All done.

2022-03-31 03:15 UTC, PaParaZz1 approved these changes

2022-03-31 03:15 UTC, merged