doc(wyh): algo02 MARL docs
opendilab/DI-engine-docs pull request #129
Opened 2022-04-29 08:14 UTC by Weiyuhong-1998

2022-05-02 05:12 UTC, puyuan1996 commented on source/02_algo/marl_zh.rst
> +考虑到在现实场景中通常会同时存在多个智能体（agent），对于强化学习的研究逐渐从单智能体领域延伸到多智能体。在多智能体强化学习（Multi-agent Reinforcement Learning, MARL）中，同时存在多个智能体与环境交互，每个智能体仍然是遵循着强化学习的目标，也就是最大化能够获得的累积回报，而此时环境全局状态（global state）的改变以及回报值（reward）就和
可以将研究多智能体合作的意义，比如可以应用到机器人，自动驾驶等领域，移到前面来？然后再阐述多智能体的模型定义，以及与单智能体的异同

2022-05-02 05:12 UTC, puyuan1996 commented on source/02_algo/marl_zh.rst
> +考虑到在现实场景中通常会同时存在多个智能体（agent），对于强化学习的研究逐渐从单智能体领域延伸到多智能体。在多智能体强化学习（Multi-agent Reinforcement Learning, MARL）中，同时存在多个智能体与环境交互，每个智能体仍然是遵循着强化学习的目标，也就是最大化能够获得的累积回报，而此时环境全局状态（global state）的改变以及回报值（reward）就和
统一回报是return, 奖励才是reward

2022-05-02 05:12 UTC, puyuan1996 commented on source/02_algo/marl_zh.rst
> +环境的不稳定性：智能体在做决策的同时，其他智能体也在采取动作，而环境状态的变化与所有智能体的联合动作相关，这会导致在MARL训练中的非平稳性
这里可以把面临的问题的英文也写在括号里面，避免歧义。

2022-05-02 05:12 UTC, puyuan1996 commented on source/02_algo/marl_zh.rst
> +目前MARL cooperation主要是采用CTDE(centralized training and decentralized execute)的方法，主要有两类解决思路，Valued-based MARL和Actor-Critic MARL。
各个算法可以加上对应文档或ding/policy.py文件的链接。

2022-05-02 05:29 UTC, puyuan1996 commented on source/02_algo/marl_zh.rst
> +对于Valued-based MARL，主要的思路是将全局的reward值分解为可以供各个agent学习的局部reward值，从而便于智能体的训练。主要有QMIX，WQMIX，QTRAN等方法。具体可参考MARL RL 算法举例。
每个算法可以用几句话概述一下核心问题与方法哈

2022-05-02 05:32 UTC, puyuan1996 commented on source/02_algo/marl_zh.rst
> +
文件名或许可以改为详细点的multi_agent_cooperation_rl_zh.rst？

2022-05-02 05:33 UTC, puyuan1996 commented on source/02_algo/marl_zh.rst
> +近年来，深度强化学习在多智能体环境和游戏中取得了巨大的成功，通过与环境进行有效的交互，我们可以得到性能卓著的智能体。例如星际争霸StarCraftII的子环境SMAC,足球游戏Gfootball,以及一些自动驾驶环境。未来，MARL还可能被更广泛地应用于资源管理、交通系统等各个领域。
中英文遵循文档的格式规范哈https://www.teambition.com/project/6204d5198009334328f97f00/tasks/scrum/62538aa3dd11ec003fbf72ef/task/6253c39ee0ccf1003f9fd88d
比如中英文之间需要有空格

2022-05-09 05:42 UTC, puyuan1996 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +考虑到在现实场景中通常会同时存在多个智能体（agent），对于强化学习的研究逐渐从单智能体领域延伸到多智能体。近年来，深度强化学习在多智能体环境和游戏中取得了巨大的成功，通过与环境进行有效的交互，我们可以得到性能卓著的智能体。例如星际争霸 StarCraftII 的子环境 SMAC ,足球游戏 Gfootball ,以及一些自动驾驶环境。未来，MARL 还可能被更广泛地应用于资源管理、交通系统等
这一块内容可以移动到【问题定义与研究动机】里面去

2022-05-09 06:43 UTC, puyuan1996 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +目前MARL cooperation主要是采用 CTDE(centralized training and decentralized execute) 的方法，主要有两类解决思路， Valued-based MARL和Actor-Critic MARL。
可以分成2个子标题。中英文之间需要添加空格哈

2022-05-09 06:48 UTC, puyuan1996 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +在以上 1, 2情况下，可以采用多个智能体之间进行通信 （MARL Communication） 的办法来进一步提高学习效率。
未来展望，或许可以加上与offline结合，智能体行为分析，智能体建模，人机协作等等。

2022-05-09 08:15 UTC, puyuan1996 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +
可以增加一个marl的算法分类图

2022-05-11 04:38 UTC, PaParaZz1 requested changes

2022-05-11 04:38 UTC, PaParaZz1 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +1. 对于一些 Agent 数量更多，更加复杂的环境如 Multi-Agent Petting Zoo,单纯的 MARL Communication 可能无法起到很好的效果
pettingzoo里有很多环境，说具体一点，而且你想指的应该是单纯的cooperation不太行，需要实时communication吧

2022-05-11 04:38 UTC, PaParaZz1 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +2. 对于一些实际情况，比如自动驾驶中，无法获得实时的全局状态，也就无法采用 CTDE 的方法进行训练
无法获得的原因说一下？比如实时获取信息带宽压力太多（尤其当agent数量变得非常大的时候）

2022-05-11 04:38 UTC, PaParaZz1 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +
加一下QPLEX

2022-05-11 04:38 UTC, PaParaZz1 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +考虑到在现实场景中通常会同时存在多个智能体（agent），对于强化学习的研究逐渐从单智能体领域延伸到多智能体。近年来，深度强化学习在多智能体环境和游戏中取得了巨大的成功，通过与环境进行有效的交互，我们可以得到性能卓著的智能体。例如星际争霸 StarCraftII 的子环境 SMAC ,足球游戏 Gfootball ,以及一些自动驾驶环境。未来，MARL 还可能被更广泛地应用于资源管理、交通系统等
用中文逗号，然后该空格的地方空格

2022-05-11 04:38 UTC, PaParaZz1 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +.. image:: images/MARL_summary.png
图片截图的时候把原图放大，截清晰一点

2022-05-11 04:38 UTC, PaParaZz1 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +环境的非稳定性：智能体在做决策的同时，其他智能体也在采取动作，而环境状态的变化与所有智能体的联合动作相关，这会导致在MARL训练中的非平稳性(non-stationary)
用有序列表吧

2022-05-11 04:38 UTC, PaParaZz1 commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +考虑到在现实场景中通常会同时存在多个智能体（agent），对于强化学习的研究逐渐从单智能体领域延伸到多智能体。近年来，深度强化学习在多智能体环境和游戏中取得了巨大的成功，通过与环境进行有效的交互，我们可以得到性能卓著的智能体。例如星际争霸 StarCraftII 的子环境 SMAC ,足球游戏 Gfootball ,以及一些自动驾驶环境。未来，MARL 还可能被更广泛地应用于资源管理、交通系统等
这里给一个smac的gif图来说明下环境吧

2022-05-12 13:23 UTC, lichuming commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +考虑到在现实场景中通常会同时存在多个智能体（agent），对于强化学习的研究逐渐从单智能体领域延伸到多智能体。近年来，深度强化学习在多智能体环境和游戏中取得了巨大的成功，通过与环境进行有效的交互，我们可以得到性能卓著的智能体。例如星际争霸 StarCraftII 的子环境 SMAC ， 足球游戏 Gfootball ， 以及一些自动驾驶环境。未来，MARL 还可能被更广泛地应用于资源管理、交通系
在很多现实场景中，人们需要控制同时存在的多个智能体（agent）来完成特定任务，如交通信控，机器人协作，自动驾驶和多人网络游戏等。因此，对强化学习的研究逐渐从单智能体领域延伸了到多智能体强化学习（Multi-agent Reinforcement Learning, MARL）。近年来，深度强化学习在多智能体环境和游戏中展现出了巨大的潜力，例如星际争霸 StarCraftII 的子环境 SMAC ， 足球游戏 Gfootball ， 以及Carla等自动驾驶的环境。

2022-05-12 13:23 UTC, lichuming commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
>  在多智能体强化学习（Multi-agent Reinforcement Learning, MARL）中，同时存在多个智能体与环境交互，每个智能体仍然是遵循着强化学习的目标，也就是最大化能够获得的累积回报，而此时环境全局状态（global state）的改变以及奖励值（reward）就和所有智能体的联合动作（joint action）相关了。因此在智能体策略学习的过程中，需要考虑联合动作的影响。
在MARL中，策略控制多个智能体同时与环境交互，且共享一个全局的回报函数。强化学习的目标仍然是最大化能够获得的累积回报，此时，环境全局状态（global state）的转移以及奖励值（reward）是和所有智能体的联合动作（joint action）而非单个智能体的动作相关的。因此在策略的学习过程中，需要探索并利用最优的联合动作。

2022-05-12 13:36 UTC, lichuming commented on source/02_algo/multi_agent_cooperation_rl_zh.rst
> +  4. 可拓展性：在大规模的多智能体系统中，就会涉及到高维度的状态空间和动作空间，对于模型表达能力和真实场景中的硬件算力有一定的要求。
1. 环境的非稳定性：智能体在做决策的同时，其他智能体也在采取动作，而环境状态的变化与所有智能体的联合动作相关。因此对于单个智能体的动作的价值评估会随着其他智能体的动作变化而变化，这会导致在MARL训练中的非平稳性(non-stationary)。

  2. 智能体获取信息的局限性：在一些环境中（例如SMAC），每个智能体不一定能够获得全局的状态信息，而是仅能获取局部的观测信息，但无法得知其他智能体的观测信息、动作等信息；

  3. 个体的目标一致性：各智能体的目标可能是最优的全局回报；也可能是各自局部回报的最优；

  4. 可拓展性：大规模的多智能体系统可能涉及到高维度的状态空间和动作空间，对于模型表达能力，算法的学习能力和真实场景中的硬件算力有一定的挑战。

2022-05-12 16:35 UTC, PaParaZz1 approved these changes

2022-05-12 16:35 UTC, merged