doc(lxl): best practice - add buffer_zh
opendilab/DI-engine-docs pull request #141
Opened 2022-05-19 10:57 UTC by lixl-st

2022-05-19 14:06 UTC, puyuan1996 commented on source/04_best_practice/buffer_zh.rst
> +这时，用户可以使用分组采样的方式实现这一目标。\ **分组采样会严重增加采样耗时**\。
在存储样本 (buffer.push) 时，每次存入一整局样本， 同时通过设置 "episode" 的分组关键字， 即可以在采样样本时 (buffer.sample) 时指定 groupby="episode" 来实现以episode为单位的采样。

2022-05-19 14:09 UTC, puyuan1996 commented on source/04_best_practice/buffer_zh.rst
> +在 Off-policy 算法中，我们通常需要使用缓存池来实现经验回放（Experience Replay）机制。
在 Off-policy RL 算法中，通常会使用经验回放（Experience Replay）机制来提高样本利用效率，为此需要定义一个缓存池来实现样本的存储，处理和采集。

2022-05-19 14:41 UTC, Will-Nie commented on source/04_best_practice/buffer_zh.rst
> +在 Off-policy 算法中，我们通常需要使用缓存池来实现经验回放（Experience Replay）机制。
First, each step of experience
is potentially used in many weight updates, which allows for greater data efficiency.
Second, learning directly from consecutive samples is inefficient, owing to the strong
correlations between the samples; randomizing the samples breaks these correlations
and therefore reduces the variance of the updates. Third, when learning on policy
the current parameters determine the next data sample that the parameters
are trained on. For example, if the maximizing action is to move left then the training
samples will be dominated by samples from the left-hand side; if the maximizing
action then switches to the right then the training distribution will also switch.
It is easy to see how unwanted feedback loops may arise and the parameters could get
stuck in a poor local minimum, or even diverge catastrophically20. By using experience 
replay the behaviour distribution is averaged over many of its previous states,
smoothing out learning and avoiding oscillations or divergence in the parameters.

补充下蒲源上面的提高样本效率（对应上面英文的第一点）， 也可以加一下第二点和第三点。

2022-05-22 10:59 UTC, PaParaZz1 requested changes

2022-05-22 10:59 UTC, PaParaZz1 commented on source/04_best_practice/buffer_zh.rst
> +此外，当用户有其它使用 buffer 缓存数据的需求时，也可以通过自定义的方式实现数据的存储与采样，例如：
介绍下dataclass吧，要不然很多人一上来不理解为什么要这样，以及具体怎么用

2022-05-22 10:59 UTC, PaParaZz1 commented on source/04_best_practice/buffer_zh.rst
> +**分组采样**
分组采样介绍一个具体的例子吧，以r2d2为例，可以看看这个入口相关的[实现](https://github.com/opendilab/DI-engine/blob/main/ding/example/r2d2.py)

2022-05-22 10:59 UTC, PaParaZz1 commented on source/04_best_practice/buffer_zh.rst
> +
再介绍下两个东西吧：
- use_count middleware
- load data when initialization（用于模仿学习，比如dqfd之类的）

2022-05-30 09:11 UTC, closed without merging