doc(rjy): outline of custom_model in best practice
opendilab/DI-engine-docs pull request #167
Opened 2022-08-24 14:12 UTC by nighood

2022-08-29 04:18 UTC, puyuan1996 commented on source/04_best_practice/custom_model.rst
> +  -  旧pipeline是修改default_model（有其他方法吗）
通过在https://github.com/opendilab/DI-engine/blob/main/ding/entry/serial_entry.py#L22 这里传入 `model`, 在这里https://github.com/opendilab/DI-engine/blob/main/ding/entry/serial_entry.py#L59 被调用

2022-08-29 04:18 UTC, puyuan1996 commented on source/04_best_practice/custom_model.rst
> +  -  比如这里需要实现 init ， forward ， 包含两个actor和critic分别对应的 forward
- 介绍一下在https://github.com/opendilab/DI-engine/tree/main/ding/model/common路径下的encoder/head文件已实现分别有哪些类，各自的用途特点是什么
- 如何通过`encoder_cls`指定encoder的类型，如何根据不同的情况调用已有的head

2022-08-29 04:18 UTC, puyuan1996 commented on source/04_best_practice/custom_model.rst
> +6. 进行测试
详细写一下如何写test，如何启动测试，如何评价测试结果

2022-08-29 04:18 UTC, puyuan1996 commented on source/04_best_practice/custom_model.rst
> +  - 比如这里选定 sac+dmc2gym+cartpole-swingup，且要求from_pixel
扩充一下文字介绍

2022-08-30 05:04 UTC, PaParaZz1 requested changes

2022-08-30 05:04 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +ding 下已实现的 policy 中均对 default_model 进行了定义，具体可看 \ `policy-default_model 链接 <https://vsde0sjona.feishu.cn/wiki/wikcnhgRDmxwU4G529aQz5BPDdh>`__\ 例如 SAC 的 default_model：
不要引入飞书链接，外部看不到

2022-08-30 05:04 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +                return 'qac', ['ding.model.template.qac']
解释下两个参数各自的含义，前者是model registry的名字，后者是model所处的文件路径

2022-08-30 05:04 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +  -  旧pipeline是修改default_model（有其他方法吗）
也是传model进去，serial_pipeline也有model参数的，不用修改default_model

2022-08-30 05:04 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +4. 根据已有的defaul_model来决定所需实现的功能
typo

2022-08-30 05:04 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +  -  比如这里需要实现 init ， forward ， 包含两个actor和critic分别对应的 forward
- 需要实现原default model中所有的方法
- 保证返回值的类型的原default model一致

2022-08-31 07:25 UTC, nighood commented on source/04_best_practice/custom_model.rst
> +  -  比如这里需要实现 init ， forward ， 包含两个actor和critic分别对应的 forward
1.encoder 和 head 的介绍有点不知道怎么写
2.“如何通过encoder_cls指定encoder的类型”？没太明白，我以为是直接`encoder_cls = ConvEncoder` ？

2022-09-04 14:21 UTC, nighood commented on source/04_best_practice/custom_model.rst
> +6. 进行测试
这里是指如何用pytest吗？

2022-09-21 09:36 UTC, PaParaZz1 requested changes

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +ding 下已实现的 policy 中均对 default_model 进行了定义，具体可看 \ `policy-default_model 链接 <https://xxx>`__\ ，例如 SAC 的 default_model：
DI-engine 中已经实现的 policy，默认使用 `default_model` 方法中表明的神经网络模型，例如在 `SACPolicy` 中：

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +此处return的 \ ``'maqac_continuous', ['ding.model.template.maqac'] ``\ ，前者是 model registry 的名字，后者是 model 所处的文件路径。
前者是模型在注册器中注册的名字，后者是模型所处的文件路径

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +policy 默认 model
Policy 默认使用的模型是什么

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +如何自定义 model 模型
如何自定义神经网络模型（model）

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +自定义 model 适用条件
如何自定义神经网络模型

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +此处return的 \ ``'maqac_continuous', ['ding.model.template.maqac'] ``\ ，前者是 model registry 的名字，后者是 model 所处的文件路径。
每第二个``之后要有一个空格

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +1. 明确 env, task, policy
去掉task

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +-  需要实现原default model中所有的方法
英文前后加空格

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +-  需要实现原default model中所有的方法
实现所有的public方法

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +    -  修改相应 policy py 文件中的 default_model ，如将 \ `ding/policy/sac:SACPolicy <https://github.com/opendilab/DI-engine/blob/main/ding/policy/sac.py>`__\ 中的 \ ``default_model``\ 为：
不用修改default_model，也是在入口中定义好model，然后作为参数传进去

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +-  todo: 详细写一下如何写test，如何启动测试，如何评价测试结果
去掉todo

2022-09-21 09:36 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +   检查输出的 \ ``q, mu, sigma``\ 的维度是否正确，以及相应的 \ ``actor``\ 和 \ ``critic``\ model 是否可微：
写个tip：
.. tip::
    同样，使用者也可以参考 DI-engine 中已有的单元测试，来熟悉相关神经网络模型的使用

2022-09-21 15:21 UTC, nighood commented on source/04_best_practice/custom_model.rst
> +    -  修改相应 policy py 文件中的 default_model ，如将 \ `ding/policy/sac:SACPolicy <https://github.com/opendilab/DI-engine/blob/main/ding/policy/sac.py>`__\ 中的 \ ``default_model``\ 为：
这里写了两种方法，一个是改default_model，一个是传入，只保留传入这个方法吗？

2022-09-21 15:28 UTC, nighood commented on source/04_best_practice/custom_model.rst
> +policy 默认 model
这里没太懂？

2022-09-22 05:47 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +    -  修改相应 policy py 文件中的 default_model ，如将 \ `ding/policy/sac:SACPolicy <https://github.com/opendilab/DI-engine/blob/main/ding/policy/sac.py>`__\ 中的 \ ``default_model``\ 为：
嗯嗯，这个比较简明

2022-09-22 05:47 UTC, PaParaZz1 commented on source/04_best_practice/custom_model.rst
> +policy 默认 model
语句直接改成我说的这个

2022-09-23 03:03 UTC, PaParaZz1 approved these changes

2022-09-23 03:04 UTC, merged