translaton(yicong): add dmc2gym english file
opendilab/DI-engine-docs pull request #174
Opened 2022-09-20 12:50 UTC by sylviai

2022-09-25 08:39 UTC, karroyan requested changes

2022-09-25 08:39 UTC, karroyan commented on source/13_envs/dmc2gym.rst
> +    - State \ ``s``\ is a real vector except for the spatial direction: math:`\cal{S} \equiv \mathbb{R}^{dim(\cal{S})}` ，where the spatial direction is represented by Unit quaternion: math:`\in SU(2)
The math formula isn't shown properly

2022-09-25 08:39 UTC, karroyan commented on source/13_envs/dmc2gym.rst
> +    - Observation \ ``o(s, a)``\ describes the observation result to the agent. The tasks we implement are all strongly observable, that is, the state can be recovered from a single observation. The
Observation describes the state that the agent can observe.

2022-09-25 08:39 UTC, karroyan commented on source/13_envs/dmc2gym.rst
> +   -  \ ``channels_first=True``\ , observation shape is \ ``[3, height, width]``\
，-> ,

2022-09-25 08:39 UTC, karroyan commented on source/13_envs/dmc2gym.rst
> +-  when \ ``from_pixels=False``\ is set，the viewing space dimension follows \ ``dim(O)``\ in the above table
when->When
the viewing space -> the observation space

2022-09-25 08:39 UTC, karroyan commented on source/13_envs/dmc2gym.rst
> +-  Concrete implementation inside the environment: For the seed of the original environment, set before calling the \ ``reset``\ method of the environment ，before the concrete \ ``reset``\
set before calling the \ ``reset``\ method of the environment ，before the concrete \ ``reset``\ -> set in the reset methods of the environment calling function, before the concrete environment implementation reset

2022-09-25 08:39 UTC, karroyan commented on source/13_envs/dmc2gym.rst
> +np_seed = 100 * np.random.randint(1, 1000).
duplicate

2022-09-29 09:09 UTC, sylviai commented on source/13_envs/dmc2gym.rst
> +np_seed = 100 * np.random.randint(1, 1000).
红色部分是删去的，绿色部分是修改过的，没有重复

2022-09-30 02:08 UTC, merged