doc(zms): add comment of Context
opendilab/DI-engine-docs pull request #177
Opened 2022-09-25 08:19 UTC by hiha3456

2022-09-26 09:39 UTC, PaParaZz1 requested changes

2022-09-26 09:39 UTC, PaParaZz1 commented on source/03_system/middleware_zh.rst
> +~~~~~~
下面这个线要比标题长

2022-09-26 09:39 UTC, PaParaZz1 commented on source/03_system/middleware_zh.rst
> +这样做的原因首先是防止在开发过程中随意在 Context 中添加新字段；其次是防止使用者使用字符串去访问 Context 中的具体字段。
这个改动的原因是：
- 防止在开发过程中随意在 Context 中添加新字段，即 ctx 中的字段必须在定义时明确清楚
- 防止使用者使用字符串去访问 Context 中的具体字段，即，禁止`ctx['xxx']` or `getattr(ctx, 'xxx')`

2022-09-26 09:39 UTC, PaParaZz1 commented on source/03_system/middleware_zh.rst
> +请在相关 Context 的 `初始化阶段 <https://github.com/opendilab/DI-engine/blob/main/ding/framework/context.py>`_ 添加。
给一个自定义 Context 类的代码例子吧

2022-09-26 09:39 UTC, PaParaZz1 commented on source/03_system/middleware_zh.rst
> +
讲一下keep的概念？

2022-09-26 09:39 UTC, PaParaZz1 commented on source/03_system/middleware_zh.rst
> +     - Before all the other middlewares
in the beginning of each middleware execution loop

2022-09-26 09:39 UTC, PaParaZz1 commented on source/03_system/middleware_zh.rst
> +   :widths: 25 25 25 25 25
调整下第三列宽度？

2022-09-26 09:40 UTC, PaParaZz1 commented
ctx介绍里少了ctx.train_output

2022-09-26 11:10 UTC, hiha3456 commented on source/03_system/middleware_zh.rst
> +这样做的原因首先是防止在开发过程中随意在 Context 中添加新字段；其次是防止使用者使用字符串去访问 Context 中的具体字段。
这里 getattr(ctx, 'xxx') 实际上还是可以调用的

2022-10-08 13:24 UTC, norman26625 commented on source/03_system/middleware_zh.rst
> +~~~~~~
‘’asd‘’

2022-10-08 13:24 UTC, norman26625 commented on source/03_system/middleware_zh.rst
> +~~~~~~
"a"

2022-10-08 13:24 UTC, norman26625 commented on source/03_system/middleware_zh.rst
> +~~~~~~
"asd" asda

2022-10-08 13:25 UTC, norman26625 commented on source/03_system/middleware_zh.rst
> +这样做的原因首先是防止在开发过程中随意在 Context 中添加新字段；其次是防止使用者使用字符串去访问 Context 中的具体字段。
``OnlineRLContext`` asdasd

2022-10-08 13:25 UTC, norman26625 commented on source/03_system/middleware_zh.rst
> +请在相关 Context 的 `初始化阶段 <https://github.com/opendilab/DI-engine/blob/main/ding/framework/context.py>`_ 添加。
``OnlineRLContext``asdasd

2022-10-18 11:13 UTC, merged