zjow(doc): Quickstart with a provided agent model
opendilab/DI-engine-docs pull request #193
Opened 2022-10-27 16:30 UTC by zjowowen

2022-10-28 03:25 UTC, PaParaZz1 requested changes

2022-10-28 03:25 UTC, PaParaZz1 commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +        main_config.exp_name = 'lunarlander_dqn_deploy'
这里逐行加一些必要的注释吧

2022-10-28 03:25 UTC, PaParaZz1 commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +从代码中可见，通过使用 torch.load 可以获得模型的 Pytorch 对象，然后使用 load_state_dict 即可将模型加载至 DI-engine 的 DQN 模型中。
PyTorch

2022-10-28 03:25 UTC, PaParaZz1 commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +我们首先使用"月球着陆器"这个环境来介绍 DI-engine 中的智能体，以及它是如何与环境交互的。
放个lunarlander的gif

2022-10-28 03:25 UTC, PaParaZz1 commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +    DI-engine 的环境管理器在对多个环境进行并行评估的时候，还会一并统计奖励的平均值，最大值和最小值，以及一些算法相关的其它指标。
给个截图？

2022-10-28 03:25 UTC, PaParaZz1 commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +让智能体变得更强
标题换换：从零训练出强大的智能体

2022-10-28 03:25 UTC, PaParaZz1 commented on source/01_quickstart/hello_world_as_an_AI_agent.rst
> +Hello World
改成这样吧 hello_world_for_DI

2022-10-28 03:25 UTC, PaParaZz1 commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +试试自己生成一个智能体模型，或许它会更强：
说一下这个的训练时间？然后说如果想要收敛更快更简单的例子，可以参考cartpole那个例子，然后给个链接

2022-10-28 03:25 UTC, PaParaZz1 commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +请继续阅读文档,来了解 DI-engine 的强化学习算法的生产框架是如何搭建的。
后续文档链接给一下加wrapper那个quick start？

2022-10-30 07:26 UTC, zjowowen commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +        main_config.exp_name = 'lunarlander_dqn_deploy'
fixed.

2022-10-30 07:26 UTC, zjowowen commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +从代码中可见，通过使用 torch.load 可以获得模型的 Pytorch 对象，然后使用 load_state_dict 即可将模型加载至 DI-engine 的 DQN 模型中。
fixed.

2022-10-30 07:26 UTC, zjowowen commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +我们首先使用"月球着陆器"这个环境来介绍 DI-engine 中的智能体，以及它是如何与环境交互的。
fixed.

2022-10-30 07:26 UTC, zjowowen commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +    DI-engine 的环境管理器在对多个环境进行并行评估的时候，还会一并统计奖励的平均值，最大值和最小值，以及一些算法相关的其它指标。
fixed.

2022-10-30 07:26 UTC, zjowowen commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +让智能体变得更强
fixed.

2022-10-30 07:27 UTC, zjowowen commented on source/01_quickstart/hello_world_as_an_AI_agent.rst
> +Hello World
fixed.

2022-10-30 07:27 UTC, zjowowen commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +试试自己生成一个智能体模型，或许它会更强：
fixed.

2022-10-30 07:27 UTC, zjowowen commented on source/01_quickstart/hello_world_as_an_AI_agent_zh.rst
> +请继续阅读文档,来了解 DI-engine 的强化学习算法的生产框架是如何搭建的。
fixed.

2022-11-02 09:01 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +只需要使用以下的代码，就可以让智能体动起来，记得要把函数中的模型地址换成本地保存的地址：
只需要使用以下的代码，就可以让智能体动起来，记得要把函数中的模型地址（附上模型地址片段）换成本地保存的地址（例如xx/xx）：
有的小白可能不知道本地地址长啥样（较为极端情况）

2022-11-02 09:02 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +决策智能是人工智能领域最重要的方向，它的一般形式是使用一个智能体来处理来自一个环境的信息，并给出合理的反馈与响应，并让环境和智能体的状态向着设计者所期望的方向变化。
最重要的方向之一？

2022-11-02 09:07 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +决策智能是人工智能领域最重要的方向，它的一般形式是使用一个智能体来处理来自一个环境的信息，并给出合理的反馈与响应，并让环境和智能体的状态向着设计者所期望的方向变化。
如果为了更有趣，可以讲智能体更加拟人化一些，举个有趣的例子

2022-11-02 09:08 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +我们首先使用"月球着陆器"这个环境来介绍 DI-engine 中的智能体，以及它是如何与环境交互的。
可以稍加一些过度引出月球登陆器，突出月球登陆的fancy和难点，以及这个环境的易上手等优点

2022-11-02 09:09 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +智能体本质上是一个接受输入，反馈输出的数学模型。它的模型由一个模型结构和一组模型参数构成。
就比如我们的脑袋，眼睛输入，嘴巴输出之类的（不一定要用这个例子，但是为了有趣可以加更多解释，不只是 说出本质或定义

2022-11-02 09:10 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +在机器学习领域的实践中，我们会把模型写入存放在一个文件中，或是从一个文件中读出所需要的智能体模型。
这里突然跳到机器学习，会有点懵；可以不用提到在xx领域我们都是怎么做的，直接说这里我们需要怎么做就可以，弱化难度和概念

2022-11-02 09:11 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +让智能体运行起来
想让你的智能体动起来吗？（这种标题会互动性更强，不一定要用我写的这句 只是举例

2022-11-02 09:12 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +    import torch
import这边也可以稍微解释下 调用了什么模块 稍加注释

2022-11-02 09:12 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +    from ding.config import compile_config
from xx import 也可以说明下，因为只用到xxx 所以from 可以怎么样，解释的更具体些

2022-11-02 09:14 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +从代码中可见，通过使用 torch.load 可以获得模型的 PyTorch 对象，然后使用 load_state_dict 即可将模型加载至 DI-engine 的 DQN 模型中。
从代码中可见，很论文写法；建议稍加修改 改为正常文章写法，弱化学术感

2022-11-02 09:15 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +从代码中可见，通过使用 torch.load 可以获得模型的 PyTorch 对象，然后使用 load_state_dict 即可将模型加载至 DI-engine 的 DQN 模型中。
为什么要加载至DI- engine可以怎么样 可以着重说明下

2022-11-02 09:16 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +然后将 DQN 模型加载到 DQN 策略中，使用评价模式的 forward_fn 函数，即可让智能体对环境状态 obs 产生反馈的动作 action 。
如果前序文档没有介绍过这些概念的话，建议给obs 动作，稍微加点类比的例子；一句话中引入了过多新概念 会让小白比较迷惑

2022-11-02 09:17 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +智能体的动作 action 会和环境进行一次交互，生成下一个时刻的环境状态 obs ，此次交互的奖励 rew ，环境是否结束的信号 done 以及其他信息 info 。
obs，rew，done，info 在第一次提到的时候要写全拼，后续才可以写缩写；例如observation（obs），reward（rew）等

2022-11-02 09:18 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +更好地评估智能体
问句会获得更好的互动性

2022-11-02 09:19 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +在强化学习中，智能体的成绩可能会随不同的初始状态而发生波动。因此，我们需要开设多个环境，从而多进行几次评估测试，来更好地为它打分。
例如在比赛中，从不同的位置出发也会获得不同的成绩；这种类比的例子可以加一下

2022-11-02 09:20 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +.. code-block:: python
in general 需要添加非常多的注释

2022-11-02 09:20 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +从零训练出强大的智能体
同上，建议使用问句

2022-11-02 09:20 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +使用 DI-engine 运行以下的代码，来获得上述测试中的智能体模型。
同上，建议增加注释

2022-11-02 09:21 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +    上述代码在 Intel i5-10210U 1.6GHz CPU 且无GPU设备的情况下大约需要10分钟训练至默认终止点。
可以放至代码块前，并进行highlight

2022-11-02 09:21 UTC, VaninaY commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +至此您已经完成了 DI-engine 的 Hello World 任务，使用了提供的代码和模型，学习了强化学习的智能体与环境是如何交互的。
多加一些鼓励的话吧

2022-11-03 13:45 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +决策智能是人工智能领域最重要的方向，它的一般形式是使用一个智能体来处理来自一个环境的信息，并给出合理的反馈与响应，并让环境和智能体的状态向着设计者所期望的方向变化。
The most important of all? Anyway, thanks, nice suggestion!

2022-11-03 13:45 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +决策智能是人工智能领域最重要的方向，它的一般形式是使用一个智能体来处理来自一个环境的信息，并给出合理的反馈与响应，并让环境和智能体的状态向着设计者所期望的方向变化。
fixed.

2022-11-03 13:45 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +我们首先使用"月球着陆器"这个环境来介绍 DI-engine 中的智能体，以及它是如何与环境交互的。
Adopted. Thanks!

2022-11-03 13:46 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +    import torch
fixed.

2022-11-03 13:46 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +让智能体运行起来
OK

2022-11-03 13:46 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +    from ding.config import compile_config
fixed.

2022-11-03 13:46 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +从代码中可见，通过使用 torch.load 可以获得模型的 PyTorch 对象，然后使用 load_state_dict 即可将模型加载至 DI-engine 的 DQN 模型中。
fixed.

2022-11-03 13:46 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +从代码中可见，通过使用 torch.load 可以获得模型的 PyTorch 对象，然后使用 load_state_dict 即可将模型加载至 DI-engine 的 DQN 模型中。
fixed.

2022-11-03 13:46 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +然后将 DQN 模型加载到 DQN 策略中，使用评价模式的 forward_fn 函数，即可让智能体对环境状态 obs 产生反馈的动作 action 。
fixed.

2022-11-03 13:47 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +更好地评估智能体
Help me please~

2022-11-03 13:48 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +在强化学习中，智能体的成绩可能会随不同的初始状态而发生波动。因此，我们需要开设多个环境，从而多进行几次评估测试，来更好地为它打分。
fixed.

2022-11-03 13:50 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +.. code-block:: python
Well, these module would be taught in detail in later chapter.
I mean, in this chapter, we hope the user could just run the codes without understanding them.
And most importantly, have fun.
I suggest not to add note in the latter two files to make codes simpler.

2022-11-03 13:51 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +从零训练出强大的智能体
I need help~

2022-11-03 13:51 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +使用 DI-engine 运行以下的代码，来获得上述测试中的智能体模型。
Reason same as above.

2022-11-03 13:52 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +至此您已经完成了 DI-engine 的 Hello World 任务，使用了提供的代码和模型，学习了强化学习的智能体与环境是如何交互的。
fixed.

2022-11-04 05:26 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +在机器学习领域的实践中，我们会把模型写入存放在一个文件中，或是从一个文件中读出所需要的智能体模型。
fixed

2022-11-07 06:48 UTC, zjowowen commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +只需要使用以下的代码，就可以让智能体动起来，记得要把函数中的模型地址换成本地保存的地址：
fixed

2022-12-22 13:27 UTC, TuTuHuss commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +更好地评估智能体
如何更好的评估智能体性能

2022-12-22 13:29 UTC, TuTuHuss commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +从零训练出强大的智能体
如何从零开始训练出强大的智能体

2022-12-22 13:32 UTC, TuTuHuss commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +    上述代码在 Intel i5-10210U 1.6GHz CPU 且无GPU设备的情况下大约需要10分钟训练至默认终止点。
使用桌面级CPU训练约十分钟即可达到默认终止点

2022-12-22 13:39 UTC, TuTuHuss commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +
这里加一个让他们改参数的地方和环境reward的介绍吧，同时可以补充一个四宫格gif用来分别展示训练的很好的gif和训练的很差的gif。

环境规定坠毁-100分；在黄旗之间登陆获得100-140分；智能体完全静止获得100分，每次喷火调整-xxx分等等。在DI-engine中，默认智能体得分达到200时结束训练。

可以修改`stop_value <https://github.com/opendilab/DI-engine/blob/main/dizoo/box2d/lunarlander/config/lunarlander_dqn_config.py#L13>`_ 来观察训练时长以及智能体表现的影响，然后尝试比我们的模型做得更好吧！

2023-01-06 06:46 UTC, TuTuHuss commented on source/01_quickstart/hello_world_for_DI_zh.rst
> +
对于代码部分，建议直接给超链接，在文档里面只用一行shell命令  python3 xxxx.py 作为引导即可

2023-01-06 06:46 UTC, TuTuHuss commented
对于代码部分，建议直接给超链接，在文档里面只用一行shell命令 python3 xxxx.py 作为引导即可

2023-01-09 10:37 UTC, merged