doc(wzl): best practice about marl
opendilab/DI-engine-docs pull request #212
Opened 2022-12-21 04:36 UTC by zerlinwang

2022-12-22 04:25 UTC, PaParaZz1 requested changes

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +``DI-zoo`` 为用户提供了一些多智能体强化学习常用环境，包括 `PettingZoo Env <https://github.com/opendilab/DI-engine/blob/main/dizoo/petting_zoo/envs/petting_zoo_simple_spread_env.py>`_ 、 `SMAC Env <https://github.com/opendil
列个表来阐述这些已支持的环境吧，可以借鉴[这里](https://github.com/Replicable-MARL/MARLlib#environments)并添加更多

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +然而在部分情况下，用户需要依据自己的业务，自己实现多智能体环境，并期待可以将其快速迁移到 ``DI-engine`` 中，以便使用 ``DI-engine`` 中的多智能体强化学习算法解决问题。本节将会介绍构建自己的多智能体强化学习环境，并利用``DI-engine``中的多智能体算法（以 `QMIX <https://github.com/opendilab/DI-engine/blob/ma
有些``之前和之后没空格，导致显示不出来

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +
说清楚是pettingzoo里的哪个环境吧

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +特殊的是，相较于单智能体环境，多智能体环境的动作空间、奖励空间和观测空间是字典，用以区分不同智能体的元素，拿``PettingZoo``的动作空间和奖励空间举例：
有时需要用字典（dict）形式来实现

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +特殊的是，相较于单智能体环境，多智能体环境的动作空间、奖励空间和观测空间是字典，用以区分不同智能体的元素，拿``PettingZoo``的动作空间和奖励空间举例：
举例的这个环境的图片放一下吧

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +当环境已经完成后，进行智能体训练只需要修改默认算法配置文件的几个参数。以 ``PettingZoo`` 下的 QMIX config文件为例：
需要找到相应的多智能体算法配置的模板（例如xxx），然后修改跟新环境相关的几个参数

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +需要修改的内容有以下几点：
需要修改的内容放上面，说完之后，提一下，完整配置文件示例如下，然后放config

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +如果想要利用 actor-critic 的 MAPPO 算法，则需要对环境作额外的改动，由于 critic 需要对每个智能体的价值做判断，而之前的全局信息不包含智能体的判别信息，即 critic 无从得知这是要对哪个智能体做出评价，因此无法计算正确的价值。为此，在环境中需要使用 ``agent_specific_global_state`` 来替代原来的 ``global_state``。还是用
对每个智能体都是相同的，不包含智能体的判别信息

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +
无法为每个智能体给出特异的价值评估

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +所谓 ``agent_specific_global_state``，就是将智能体自己的局部观测与全局状态进行叠加，这样 ``global_state`` 就既有智能体的判别信息，也具有足够的全局信息来让 critic 给出正确的价值。
就是 -> 一种常用的实现

2022-12-22 04:25 UTC, PaParaZz1 commented on source/04_best_practice/marl_zh.rst
> +相较于 QMIX 的改动外，唯一的区别就是增加了对于 ``agent_specific_global_state=True`` 的判断。
就是新增了配置项 xxx

2022-12-22 11:33 UTC, zerlinwang commented
关于表格的形式，模仿了其它doc中表格的写法。但是rst的表格似乎非常麻烦，最后不确定是否正确渲染，如果有问题请指出。

2022-12-23 09:07 UTC, puyuan1996 commented on source/04_best_practice/marl_zh.rst
> +其它的内容与环境无关，直接照搬就可以运行，完整的配置文件示例如下：
其它的内容与环境无关，直接使用原设置即可 (当然不同环境 MARL 算法的最优参数一般也会不同，如果需要好的性能可能需要调整参数)，完整的配置文件示例如下：

2022-12-23 09:07 UTC, puyuan1996 commented on source/04_best_practice/marl_zh.rst
> +当环境已经完成后，进行智能体训练只需要找到相应的多智能体算法配置的模板，然后修改跟新环境相关的几个参数即可。例如如果想要使用 QMIX 算法，那么可以找到 ``PettingZoo`` 下的 QMIX config `ptz_simple_spread_qmix_config.py https://github.com/opendilab/DI-engine/blob/main/dizoo/pe
QMIX MAPPO 分成2个小标题

2022-12-23 09:07 UTC, puyuan1996 commented on source/04_best_practice/marl_zh.rst
> +
DI-engine 已经实现的 MARL 算法或许可以用表格的形式列出，例如每列分别为
- 算法名 (原论文连接)， 算法简介，DI-engine 中的 policy 路径，已经有对应config的环境

2022-12-23 09:07 UTC, puyuan1996 commented on source/04_best_practice/marl_zh.rst
> +相较于 QMIX 的改动外，唯一的区别就是增加了配置项 ``agent_specific_global_state=True`` 。
增加一段结束语？

2022-12-27 03:20 UTC, PaParaZz1 requested changes

2022-12-27 06:53 UTC, zerlinwang commented on source/04_best_practice/marl_zh.rst
> ++==========================================================================================================================================+=====================================+=====================
不同子环境可能情况不同，既包含全局观测的子环境，也包含部分观测的子环境

2022-12-27 09:45 UTC, PaParaZz1 approved these changes

2022-12-27 09:45 UTC, merged