add metadrive documentation in chinese
opendilab/DI-engine-docs pull request #222
Opened 2023-02-10 13:59 UTC by timothijoe

2023-02-12 10:51 UTC, puyuan1996 requested changes

2023-02-12 10:51 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +`Metadrive <https://metadrive-simulator.readthedocs.io/en/latest/index.html>`_ , 是一种高效的驾驶模拟器, 支持生成具有各种道路和交通设置的无限场景.
- 中文文档使用中文的逗号，句号。中英文之间加上一个空格。
- Metadrive -> MetaDrive?
- 文字尽量准确简洁，可以使用有序/无序列表。当英文不容易翻译时，加上英文原文。

是一个高效的组合式 (Compositional) 的驾驶模拟器，驾驶的目标是控制一辆（或者多辆）汽车安全且按时地从起点开到终点。它具有以下关键特性: 
- 组合式: 它支持生成具有各种道路地图和交通设置的无限场景，可用于 RL 泛化性的研究。
- 轻量化：易于安装和运行。它在标准 PC 上可以运行高达 300 FPS。
- 高逼真：精确的物理模拟和多种类型的输入，包括激光雷达、RGB 图像、自上而下的语义地图和第一人称视角图像。用户可以自行选择强化学习中的 observation 的种类。

以下主要以观测输入 (observation) 是语义地图的情况展开介绍。

2023-02-12 10:51 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +道路的随机性：根据随机种子的不同，车道线的数目，道路不同模块的拼接，以及终点的选择都会有所变化．
车辆的观察空间为259维的 numpy 数组，数据类型为 ``float32``，obs shape 为 `(259,)`。观察空间包含以下3部分内容：

-  ego_state：即当前状态，例如航向，转向，速度和到边界的相对距离。
-  navigation：即导航信息，引导车辆驶向目的地的检查点 (checkpoints)。
-  surrounding：即周围的信息，由激光雷达生成，通常使用240个激光 (single agent) 扫描半径50米的临近区域。

初始时刻的随机性：
- 车辆会随机初始化到一条道路的某一条车道线上。
- 道路的随机性：根据随机种子的不同，车道线的数目，道路不同模块的拼接，以及终点的选择都会有所变化。

2023-02-12 10:51 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +-  surrounding,　即周围的信息，由激光雷达生成，通常使用240个激光(single agent)扫描半径50米的临近区域
single agent？

2023-02-12 10:51 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +道路的随机性：根据随机种子的不同，车道线的数目，道路不同模块的拼接，以及终点的选择都会有所变化．
格式按上面这样，再优化一下文字

2023-02-12 10:51 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +  那么每个代理的动作空间将变为 Box(-1.0, 1.0, shape=(3, ))。 这允许用户编写引入更多输入操作维度的环境包装器。
MetaDrive 环境的动作空间是2维的连续动作，其有效范围为[-1, 1]：
- 第一个维度代表转向角 (steering)。当动作取1或者-1时分别代表方向盘向左或者向右转到最大转向角度，取０的时候代表方向盘朝向正前方。
- 第二个维度代表加速或者刹车。当范围在(0,1)区间时候代表加速，范围在(-1,0)代表刹车；取0的时候代表不采取任何动作。
通过这样的设计，每个智能体的动作空间都被固定为 gym.spaces.Box(low=-1.0, high=1.0, shape=(2, ))。同时，它也提供了 一个名为 extra_action_dim (int) 的配置，例如，如果我们设置 config["extra_action_dim"] = 1，那么每个智能体的动作空间将变为 Box(-1.0, 1.0, shape=(3, ))。 这允许用户编写引入更多输入操作维度的环境包装器。

2023-02-12 10:51 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +  那么每个代理的动作空间将变为 Box(-1.0, 1.0, shape=(3, ))。 这允许用户编写引入更多输入操作维度的环境包装器。
增加的动作维度的作用是什么？怎么作用到车上？

2023-02-12 10:51 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +
按下面给出的示例修改结构与文字:

MetaDrive 中默认的奖励函数包含了一个密集的（驾驶过程中的）奖励和一个稀疏的终局奖励。
- 密集奖励反映了在每一个 step 下，车辆在 Frenet 坐标中朝向目的地的纵向运动的程度。
- 终端奖励只有在车辆成功到达目的地的时候得到。(怎么具体指定，值为多少？)

事实上，Metadrive 提供了一个复杂的奖励函数，我们可以从c onfig dict 里面自定义他们的奖励函数，完整的奖励函数由以下四个部分构成：

- 驾驶奖励 (driving reward)：在t-1到t时刻，在当前车道线开出的纵向距离，它是一个密集奖励。
- 速度奖励 (speed reward)：当前时刻的速度，速度越大，则奖励越大，它也是一个密集奖励。
- 横向比例 (use_lateral_reward): 它是 [0, 1] 范围内的乘数 (???)，指示自我车辆是否远离当前车道的中心，与驾驶奖励配合使用，如果为True，则驾驶奖励的大小不仅取决于纵向路程，还取决于横向坐标与车道线正中间的距离。
- 终止奖励 (terminaltion reward)：在 episod e结束时候，其他密集奖励将被禁用，并根据车辆的状态返回一个奖励。
  - 具体的情况可以分为：到达终点(sucess_reward),　开出道路(out_of_road_penalty)，撞车(crash_vehicle_penalty)，撞到其他障碍物(crash_object_penalty)。当遇到以上四种情况的时候游戏终止，同时根据情况返回奖励或惩罚。

2023-02-12 10:51 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +汽车的观察空间定义为俯视图，大小为 5x84x84，其中5代表了通道数，后两个维度(84x84)代表了每个通道的图片的大小．
应该是观察空间无变化，下面以 xxx 为例详细介绍各部分的含义。

2023-02-12 10:51 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +    from easydict import EasyDict
根据修改后的代码更新一下

2023-02-13 12:04 UTC, puyuan1996 requested changes

2023-02-13 12:04 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +- 组合式: 它支持生成具有各种道路地图和交通设置的无限场景，可用于 RL 泛化性的研究。
*的（理论上可以是无限的）场景

2023-02-13 12:04 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +- 轻量化：易于安装和运行。它在标准 PC 上可以运行高达 300 FPS。
FPS (*英文原文)

2023-02-13 12:04 UTC, puyuan1996 commented on source/13_envs/metadrive_zh.rst
> +具体细节，可以参考 metadrive 的代码实现 `Metadrive <https://github.com/metadriverse/metadrive/blob/main/metadrive/envs/metadrive_env.py>`_.
*MetaDrive

2023-02-14 08:55 UTC, PaParaZz1 requested changes

2023-02-14 08:55 UTC, PaParaZz1 commented on source/13_envs/index_zh.rst
> +   metadrive_zh.rst
remove `.rst` suffix

2023-02-14 08:55 UTC, PaParaZz1 commented on source/13_envs/metadrive_zh.rst
> +随机性：
随机性是不是放到其他那里

2023-02-14 08:55 UTC, PaParaZz1 commented on source/13_envs/metadrive_zh.rst
> +    目前 DI-engine 只支持离散动作空间版本， 后续会补充关于连续空间的版本及一些适配。
这个注释删了？

2023-02-14 16:02 UTC, timothijoe commented on source/13_envs/metadrive_zh.rst
> +汽车的观察空间定义为俯视图，大小为 5x84x84，其中5代表了通道数，后两个维度(84x84)代表了每个通道的图片的大小．
观察空间有变化的，从原有的259维度的vector变成了5x84x84的image

2023-02-14 16:08 UTC, timothijoe commented on source/13_envs/metadrive_zh.rst
> +
这只是官方的说明，笔者翻译了一下，笔者也不知道能增加什么额外动作

2023-02-15 01:41 UTC, PaParaZz1 approved these changes

2023-02-15 01:41 UTC, merged