doc(zc): Add edac_zh
opendilab/DI-engine-docs pull request #238
Opened 2023-05-23 02:59 UTC by Super1ce

add edac_zh.rst

2023-05-23 06:39 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +离线强化学习（RL）是一个重新出现的研究领域，旨在使用大量先前收集的数据集来学习行为，而无需进一步与环境进行交互。
“重新”还是“新”？

2023-05-23 06:40 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +它有可能在许多实际决策问题中取得巨大进展，其中主动数据收集昂贵（例如，在机器人，药物发现，对话生成，推荐系统中）或危险（例如，医疗保健，自动驾驶或教育）。
优化以下表述：

“它有可能在许多实际决策问题中取得巨大进展，其中主动数据收集昂贵”
->
“它有可能解决许多实际决策问题，尤其是哪些数据收集较为昂贵的应用问题”

2023-05-23 06:42 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +它有可能在许多实际决策问题中取得巨大进展，其中主动数据收集昂贵（例如，在机器人，药物发现，对话生成，推荐系统中）或危险（例如，医疗保健，自动驾驶或教育）。
“或危险（例如，医疗保健，自动驾驶或教育）”

->

"或是那些具有危险性的应用问题（例如，医疗保健，自动驾驶）"

2023-05-23 06:43 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +此外，在线收集的数据量远远低于离线数据集。这样的范式有望解决将强化学习算法从受限实验室环境带到现实世界的关键挑战。
“此外，在线收集的数据量远远低于离线数据集。”
->
"此外，对于一些环境，在线收集的数据量远远低于离线数据集。"

2023-05-23 06:47 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +此外，在线收集的数据量远远低于离线数据集。这样的范式有望解决将强化学习算法从受限实验室环境带到现实世界的关键挑战。
“这样的范式”
->
"离线强化学习的范式"

“受限实验室环境”
->
"实验室环境"

"这样的范式有望解决将强化学习算法从受限实验室环境带到现实世界的关键挑战"
->
"离线强化学习的范式有望解决将强化学习算法从实验室带入现实世界的关键挑战"

2023-05-23 06:48 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +然而，在离线设置中直接使用现有的基于价值的离策略 RL 算法通常会导致性能不佳，这是由于从分布外操作引导和过度拟合等问题。
“离策略”->"离线策略"

“分布外操作引导” 添加英文说明

2023-05-23 06:49 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +因此，许多约束技术（例如政策约束；保守估计；不确定性估计）被添加到基本在线 RL 算法中。 基于不确定性的离线强化学习与多
“政策约束” -> "策略约束"

2023-05-23 06:50 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +是其中之一，它通过添加更多批评网络来惩罚分布外（OOD）操作。
“批评网络” -> "评价网络"

2023-05-23 06:52 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +2. EDAC 可以在许多 SAC RL 算法之上用不到20行代码实现
标点符号？

2023-05-23 06:53 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +Q 网络的数量会表现得更好。这些结果的图形如下：
“这些结果的图形如下” -> "如下图所示"

2023-05-23 06:54 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +EDAC 表明，通过增加批评家的数量，可以通过剪切 Q 学习 :math:`min_{j=1,2}Q(s,a)` 来惩罚 OOD 操作。 因此，EDAC 可以通过在标准 SAC RL 算法上集成 Q 网络并添加惩罚项来惩罚 OOD 操作来实现。
“剪切 Q 学习” 添加英文说明

2023-05-23 06:57 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +.. _`EDAC release repo`: https://github.com/snu-mllab/EDAC
有一些地方英汉直译效果不佳，建议使用chatgpt优化一下相关表述。

2023-05-23 06:57 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +伪代码显示在算法1中，与传统的演员评论家算法（例如 SAC）的区别以蓝色显示。
“演员评论家” 建议与DI-engine-docs 统一表述

2023-05-23 07:26 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +EDAC 通过增加 SAC 算法中 Q 网络的数量来显示剪切 Q 学习的重要性。通过计算 clipe 惩罚和 OOD 操作和数据集操作的标准偏差，论文显示为什么算法通过增加
"clipe" -> "clip"

2023-05-23 07:27 UTC, zjowowen commented on source/12_policies/edac_zh.rst
> +离线强化学习（RL）是一个新出现的研究领域，旨在使用大量先前收集的数据集来学习行为，而无需进一步与环境进行交互。
"（RL）" -> "（offline-RL）"

2023-05-24 03:34 UTC, PaParaZz1 requested changes

2023-05-24 03:34 UTC, PaParaZz1 commented on source/12_policies/edac_zh.rst
> +2. EDAC 可以在许多 SAC RL 算法之上用不到20行代码实现。
在 SAC 及相关衍生算法之上

2023-05-24 03:34 UTC, PaParaZz1 commented on source/12_policies/edac_zh.rst
> +EDAC
index_zh.rst里加一下edac吧

2023-05-24 03:34 UTC, PaParaZz1 commented on source/12_policies/edac_zh.rst
> +EDAC 表明，通过增加批评家的数量，可以通过剪切 Q 学习（clipped Q-learning） :math:`min_{j=1,2}Q(s,a)` 来惩罚 OOD 操作。 因此，EDAC 可以通过在标准 SAC RL 算法上集成 Q 网络并添加惩罚项来惩罚 OOD 操作来实现。
剪切->截断

2023-05-24 03:34 UTC, PaParaZz1 commented on source/12_policies/edac_zh.rst
> +的总和，这等于总方差。 上述方程等同于最小化第一幅图的方程。
这等于总方差 -> 这等价于最大化总方差。因此，

2023-05-24 03:34 UTC, PaParaZz1 commented on source/12_policies/edac_zh.rst
> +为了有效地增加近分布 OOD 操作的 Q 值方差，EDAC 最大化以下方程：
近分布 -> 邻近原始数据集分布

2023-05-24 03:34 UTC, PaParaZz1 commented on source/12_policies/edac_zh.rst
> +是其中之一，它通过添加更多评价网络来惩罚分布外（OOD）操作。
评价网络（Critic Network）

2023-05-24 03:34 UTC, PaParaZz1 commented on source/12_policies/edac_zh.rst
> +EDAC 表明，通过增加批评家的数量，可以通过剪切 Q 学习（clipped Q-learning） :math:`min_{j=1,2}Q(s,a)` 来惩罚 OOD 操作。 因此，EDAC 可以通过在标准 SAC RL 算法上集成 Q 网络并添加惩罚项来惩罚 OOD 操作来实现。
批评家都改成 Critic 吧

2023-05-25 03:39 UTC, PaParaZz1 approved these changes

2023-05-25 03:39 UTC, merged