translate doc(zt): add rainbow and iqn ch
opendilab/DI-engine-docs pull request #242
Opened 2023-06-09 05:24 UTC by timothijoe

translate rainbow and iqn into Chinese

2023-06-10 11:54 UTC, PaParaZz1 requested changes

2023-06-10 11:54 UTC, PaParaZz1 commented on source/12_policies/iqn_zh.rst
> +IQN (Implicit Quantile Network)和QRDQN (Quantile Regression DQN)之间的关键区别在于，IQN引入了隐式量化网络（Implicit Quantile Network），它是一个确定性参数化函数，通过训练将来自基本分布（例如在U([0, 1])上的tau）的样本重新参数化为目标分布的相应分位数值，而QRDQN直接学习了一组预定义的固定分位数
中英文混杂，英文左右各有一个空格

2023-06-10 11:54 UTC, PaParaZz1 commented on source/12_policies/iqn_zh.rst
> +IQN (Implicit Quantile Network)和QRDQN (Quantile Regression DQN)之间的关键区别在于，IQN引入了隐式量化网络（Implicit Quantile Network），它是一个确定性参数化函数，通过训练将来自基本分布（例如在U([0, 1])上的tau）的样本重新参数化为目标分布的相应分位数值，而QRDQN直接学习了一组预定义的固定分位数
中间加一句 distributional RL 的研究目标描述？

2023-06-10 11:54 UTC, PaParaZz1 commented on source/12_policies/iqn_zh.rst
> +  - 多步时序差分 (TD)损失
括号右边空格

2023-06-10 11:54 UTC, PaParaZz1 commented on source/12_policies/rainbow_zh.rst
> +Rainbow 是在 `Rainbow: Combining Improvements in Deep Reinforcement Learning <https://arxiv.org/abs/1710.02298>`_. 它将许多独立的改进方法应用于DQN，包括： Double DQN, priority, dueling head, multi-step TD-loss, C51 (分布式
不是分布式，分布式是distributed，这里是distributional，不如就用原词

2023-06-13 06:38 UTC, zhangpaipai commented on source/12_policies/iqn_zh.rst
> +4. 通常情况下， IQN 使用 **eps-greedy** 或 **多项式采样** 进行探索。
多项式采样后面加个括号（multinomial sample）？

2023-06-13 06:38 UTC, zhangpaipai commented on source/12_policies/iqn_zh.rst
> +        是否优先级经验回放（PER）能够提升IQN的性能取决于任务和训练策略。
IQN前后加个空格？

2023-06-13 06:49 UTC, zhangpaipai commented on source/12_policies/rainbow_zh.rst
> +然后，我们将多步分布式损失与双重DQN相结合，通过使用在线网络选择贪婪动作，并使用目标网络评估该动作。KL损失也被用来优先选择转换：
分布式都改成distributional?

2023-06-13 06:49 UTC, zhangpaipai commented on source/12_policies/rainbow_zh.rst
> +然后，我们将多步分布式损失与双重DQN相结合，通过使用在线网络选择贪婪动作，并使用目标网络评估该动作。KL损失也被用来优先选择转换：
双重DQN改成Double?

2023-06-13 07:28 UTC, zhangpaipai commented on source/12_policies/rainbow_zh.rst
> +DQN 从经验回放缓冲区均匀地进行采样。理想情况下，我们希望更频繁地采样那些有更多可学习内容的 transition。作为评估学习潜力的一种替代方法，优先级经验回放会根据最新的绝对 TD 误差的相对概率来采样对应的transition，具体而言：
相对概率改成概率？

2023-06-13 07:29 UTC, zhangpaipai commented on source/12_policies/rainbow_zh.rst
> +在这里， :math:`\Phi_{\boldsymbol{z}}` 目标分布在固定支持 :math:`\boldsymbol{z}` 上的L2投影。
加个 是

2023-06-13 07:30 UTC, zhangpaipai commented on source/12_policies/rainbow_zh.rst
> +随着时间的推移，网络可以学习忽略噪声流，但在状态空间的不同部分以不同的速率进行学习，从而实现一种自适应的状态条件探索，即一种自退火机制。当动作空间很大时，例如在　Montezuma's Revenge 等游戏中噪声网络通常比 :math:`\epsilon`-greedy 方法取得更好的改进效果，这是由于 :math:`\epsilon`-greedy　往往会在收集足够数量的动作奖励之前迅速收敛
有的英文前后打了2个空格

2023-06-25 12:39 UTC, PaParaZz1 approved these changes

2023-06-25 12:39 UTC, merged