translate(zt): add sql_zh
opendilab/DI-engine-docs pull request #243
Opened 2023-06-30 06:44 UTC by timothijoe

Add sql zh translate into main

2023-07-06 05:41 UTC, PaParaZz1 requested changes

2023-07-06 05:41 UTC, PaParaZz1 commented on source/12_policies/sql_zh.rst
> +4. SVGD 已被采用于从具有 **连续动作空间** 的软Q函数中进行采样。
不如就用 soft Q

2023-07-06 05:41 UTC, PaParaZz1 commented on source/12_policies/sql_zh.rst
> +SQL考虑了一个更通用的最大熵策略，使得最优策略在每个访问的状态下都旨在最大化其熵值：
一开始补充下最大熵思想的目的吧

2023-07-06 05:41 UTC, PaParaZz1 commented on source/12_policies/sql_zh.rst
> +    - 探索技术, 例如ε-贪婪或 OU 噪声 (这些技术可以在原始论文中找到;请参考  `Continuous control with deep reinforcement learning <https://arxiv.org/abs/1509.02971>`_ 和 `On the theory of the Brownian motion <https://link.aps.org/
“找到”后面的分号不对

2023-07-06 05:41 UTC, PaParaZz1 commented on source/12_policies/sql_zh.rst
> +    - SQL可以与演示数据结合使用，用于提出一种模仿学习算法: SQIL， 该算法在以下论文中提出： `SQIL: Imitation Learning via Reinforcement Learning with Sparse Rewards <https://arxiv.org/abs/1905.11108>`_ 。  请参考DI-engine实现中的SQIL代码，链接： `SQIL
该有的空格要有

2023-07-06 05:41 UTC, PaParaZz1 commented on source/12_policies/sql_zh.rst
> + - Lunarlander和Pong的停止值分别为200和20。
解释下停止值的含义

2023-07-06 05:41 UTC, PaParaZz1 commented on source/12_policies/sql_zh.rst
> + - 同时打开： 使用 cuda = True 和 base env manager = subprocess。
这个同时xxx都删掉吧

2023-07-11 01:39 UTC, Cloud-Pku commented on source/12_policies/sql_zh.rst
> +    - 探索技术, 例如ε-贪婪或 OU 噪声 (这些技术可以在原始论文中找到;请参考  `Continuous control with deep reinforcement learning <https://arxiv.org/abs/1509.02971>`_ 和 `On the theory of the Brownian motion <https://link.aps.org/
每一项可结合的内容前或许可以起一个小标题，代表这项技术的名称

2023-07-11 01:39 UTC, Cloud-Pku commented on source/12_policies/sql_zh.rst
> +其中 :math:`q_{s_{t}}` 和 :math:`q_{a_{t}}` 在分别空间 :math:`\mathrm{S}` 和 :math:`\mathrm{A}` 是正数。
分别在空间 *** 和 *** 中是处处大于0的

2023-07-11 01:39 UTC, Cloud-Pku commented on source/12_policies/sql_zh.rst
> +Stein variational gradient descent (SVGD) 被用于学习一个随机采样网络，该网络近似从该分布中采集样本。
该分布是指玻尔兹曼分布吗？

2023-07-25 04:30 UTC, PaParaZz1 approved these changes

2023-07-25 04:30 UTC, merged