translate doc (cy): add td3 zh translation
opendilab/DI-engine-docs pull request #244
Opened 2023-07-05 10:48 UTC by Cloud-Pku

2023-07-06 05:35 UTC, PaParaZz1 requested changes

2023-07-06 05:35 UTC, PaParaZz1 commented on source/12_policies/td3_zh.rst
> +参考
参考文献

2023-07-06 05:35 UTC, PaParaZz1 commented on source/12_policies/td3_zh.rst
> +4. 目标策略平滑正则
有些术语在中文翻译之后括号加一下英文原词吧

2023-07-06 05:35 UTC, PaParaZz1 commented on source/12_policies/td3_zh.rst
> +    我们通过 ``_init_learn`` 中的目标模型初始化来实现目标网络。
某些代码里的实际变量（比如 self._target model）还是不翻译了吧，就用英文原词

2023-07-06 05:35 UTC, PaParaZz1 commented on source/12_policies/td3_zh.rst
> +        我们通过配置 ``random-collect-size`` 来控制初始经验回放池中的 transition 数目。
加一下这个操作的目的

2023-07-06 05:35 UTC, PaParaZz1 commented on source/12_policies/td3_zh.rst
> +TD3 提出了一个截断双 Q 学习变体（Clipped Double-Q Learning），它利用了这样一个概念，即遭受高估偏差的值估计可以用作真实值估计的近似上限。TD3表明，目标网络是深度 Q 学习方法中的一种常见方法，通过减少误差积累来减少方差是至关重要的。
即遭受高估偏差的值估计可以用作真实值估计的近似上限，这句话有点迷惑，是不是得再加点解释

2023-07-06 13:29 UTC, zhangpaipai commented on source/12_policies/td3_zh.rst
> +首先，为了解决动作价值估计和策略提升的耦合问题，TD3建议延迟策略更新，直到动作价值估计值尽可能小。因此，TD3只在固定数量 :math:`d` 的 critic 网络更新后更新策略和目标网络。
改成固定数量的次数可能更通顺一点

2023-07-06 13:30 UTC, zhangpaipai commented on source/12_policies/td3_zh.rst
> +TD3 提出了一个截断双 Q 学习变体（Clipped Double-Q Learning），它利用了这样一个概念，即遭受高估偏差的值估计可以用作真实值估计的近似上限。TD3表明，目标网络是深度 Q 学习方法中的一种常见方法，通过减少误差积累来减少方差是至关重要的。
减少方差改成减少目标的方差？

2023-07-06 13:33 UTC, zhangpaipai commented on source/12_policies/td3_zh.rst
> +最后，确定性策略的一个问题是，它们可能会过拟合，以缩小价值估计中的峰值。当更新 critic 网络时，使用确定性策略的学习目标极易受到函数近似误差引起的不准确性的影响，从而增加了目标的方差。
要不过拟合讲的具体点是什么过拟合？为什么会减小价值中的峰值？

2023-07-06 13:36 UTC, zhangpaipai commented on source/12_policies/td3_zh.rst
> +TD3 引入了一种用于深度价值学习的正则化策略，即目标策略平滑，它模仿了SARSA的学习更新。具体来说，TD3通过在目标策略中添加少量随机噪声并在以下小批次中取平均值来近似此期望：
以下小批次取平均好像在下面的公式体现不出来，要不换种表述或者改下公式？

2023-07-10 09:37 UTC, Cloud-Pku commented on source/12_policies/td3_zh.rst
> +最后，确定性策略的一个问题是，它们可能会过拟合，以缩小价值估计中的峰值。当更新 critic 网络时，使用确定性策略的学习目标极易受到函数近似误差引起的不准确性的影响，从而增加了目标的方差。
这里原文就这么一句
“A concern with deterministic policies is they can overfit to narrow peaks in the value estimate. When updating the
critic, a learning target using a deterministic policy is highly susceptible to inaccuracies induced by function approximation error, increasing the variance of the target. This induced variance can be reduced through regularization”，
我理解的是训练过程中policy为了让action相应的value相近（峰值间差距缩小），会使policy输出的action直接拟合到buffer中带来较大value的动作

2023-07-11 04:54 UTC, PaParaZz1 approved these changes

2023-07-11 04:54 UTC, merged