translatation(zp): add fqf zh translation
opendilab/DI-engine-docs pull request #245
Opened 2023-07-13 07:02 UTC by zhangpaipai

2023-07-14 06:52 UTC, Super1ce commented on source/12_policies/fqf_zh.rst
> +3. FQF 是一种 **异策略（off-policy）** 算法。
感觉 off-policy 可以直接不翻译

2023-07-17 10:26 UTC, Super1ce commented on source/12_policies/fqf_zh.rst
> +FQF 首次在论文 `Fully Parameterized Quantile Function for Distributional Reinforcement Learning <https://arxiv.org/pdf/1911.02140>`_ 中被提出。 FQF 和 IQN 的主要区别在于，FQF 额外引入了 the fraction proposal network，这是一个被训练
IQN 把全名写一下

2023-07-17 10:26 UTC, Super1ce commented on source/12_policies/fqf_zh.rst
> +   :scale: 100%
简单介绍一下这个图

2023-07-18 03:05 UTC, PaParaZz1 requested changes

2023-07-24 07:03 UTC, PaParaZz1 approved these changes

2023-07-24 07:03 UTC, merged