translation(zc)： add qmix_zh translation
opendilab/DI-engine-docs pull request #247
Opened 2023-07-17 14:27 UTC by Super1ce

add qmix_zh

2023-07-18 09:50 UTC, PaParaZz1 requested changes

2023-07-18 09:50 UTC, PaParaZz1 commented on source/12_policies/index_zh.rst
> +    qmix_zh
添加多智能体小版块

2023-07-18 13:14 UTC, PaParaZz1 commented on source/12_policies/qmix_zh.rst
> +6. QMIX 使用由 **智能体网络、混合网络、超网络** 组成的架构来表示联合价值函数。 混合网络是一个前馈神经网络，它将智能体网络的输出作为输入并单调地混合它们，产生联合动作值。 混合网络的权重由单独的超网络产生。
一些特有的英文名词备注在括号里吧

2023-07-18 13:15 UTC, PaParaZz1 commented on source/12_policies/qmix_zh.rst
> +1. 上述结果是通过在五个不同的随机种子 (0, 1, 2) 上运行相同的配置获得的。
五个种子，但括号里怎么就三个

2023-07-25 07:16 UTC, Super1ce commented on source/12_policies/qmix_zh.rst
> +1. 上述结果是通过在五个不同的随机种子 (0, 1, 2) 上运行相同的配置获得的。
他英文那里就只写了三个。。。

2023-07-26 06:14 UTC, Mossforest commented on source/12_policies/qmix_zh.rst
> +) 相比，QMIX 在训练过程中可以表示更多的额外状态信息，并且可以表示更丰富的动作价值函数类。
“表示更多的额外状态信息”有些模糊，应该是指混合网络输入的全局信息让QMIX在训练过程中能够访问并运用更多的额外（智能体观察范围外）信息状态，按照这个意思再改一下；原英文版本也可以同步修改一下

2023-07-26 06:21 UTC, Mossforest commented on source/12_policies/qmix_zh.rst
> +6. QMIX 使用由 **智能体网络(agent networks)、混合网络(a mixing network)、超网络(a hyper-network)** 组成的架构来表示联合价值函数。 混合网络是一个前馈神经网络，它将智能体网络的输出作为输入并单调地混合它们，产生联合动作值。 混合网络的权重由单独的超网络产生。
mixing network & hyper network前面的a可以删掉

2023-07-26 06:27 UTC, Mossforest commented on source/12_policies/qmix_zh.rst
> +
缺少了一段原文：
"Each weight of the mixing network is produced by a independent hyper-network, which takes the global state as input and outputs the weight of one layer of the mixing network. More details can be found in the original paper [Rashid et al.(2018)](https://arxiv.org/abs/1803.11485)."

2023-07-26 07:46 UTC, merged