doc(luyd): add SafeRL doc
opendilab/DI-engine-docs pull request #255
Opened 2023-10-13 07:34 UTC by AltmanD

Add saferl doc in zh

2023-10-16 05:26 UTC, PaParaZz1 requested changes

2023-10-16 05:26 UTC, PaParaZz1 commented on source/02_algo/safe_rl_zh.rst
> +安全强化学习（Safe Reinforcement Learning），是强化学习的一个细分发展方向，与强化学习一样是一个最大化预期回报的策略学习过程。强化学习在现实世界中，如自动驾驶和机器人场景中，部署时通常会引发安全问题。安全强化学习主要的研究目标就是如何在学习和部署过程中既能确保合理的系统性能又能符合安全条件的约束。
安全强化学习（Safe Reinforcement Learning），是强化学习的一个细分发展方向。强化学习的核心目标是学习一个最大化预期回报的策略，但是在现实世界的决策问题，例如自动驾驶和机器人场景中，部署这种仅最大化预期回报的智能体通常会引发安全问题。

2023-10-16 05:26 UTC, PaParaZz1 commented on source/02_algo/safe_rl_zh.rst
> +
关键词，或者小标题，考虑加粗

2023-10-16 05:26 UTC, PaParaZz1 commented on source/02_algo/safe_rl_zh.rst
> +安全强化学习通常被建模为约束马尔科夫决策过程（CMDP），约束马尔科夫决策过程（CMDP）是马尔科夫决策过程（MDP）的扩展，由六元组 :math:`(S, A, P, r, c, \mu)`，即状态空间、动作空间、状态转移函数、奖励、代价、代价阈值组成。智能体采取动作后不仅会收到奖励 r 还会得到代价 c ，策略目标是在不超过代价阈值的约束条件下最大化长期奖励：
CMDP写一下全称

2023-10-16 05:26 UTC, PaParaZz1 commented on source/02_algo/safe_rl_zh.rst
> +上图是 OpenAI 发布的 safety-gym 环境，传统强化学习训练出的最优策略往往以任务为中心，不考虑对环境和自身的影响、不会考虑是否符合人类预期等等。小车（红色）会以最快速度移动到目标地点（绿色圆柱体），完全没有避开地面的陷阱区域（蓝色圆圈），移动路径上如果有障碍物（青色立方体）则会撞开或强行从边缘擦过。
加引用

2023-10-16 07:10 UTC, Cloud-Pku commented on source/02_algo/safe_rl_zh.rst
> +安全强化学习通常被建模为约束马尔科夫决策过程（CMDP），约束马尔科夫决策过程（CMDP）是马尔科夫决策过程（MDP）的扩展，由六元组 :math:`(S, A, P, r, c, \mu)`，即状态空间、动作空间、状态转移函数、奖励、代价、代价阈值组成。智能体采取动作后不仅会收到奖励 r 还会得到代价 c ，策略目标是在不超过代价阈值的约束条件下最大化长期奖励：
定义里没有折扣因子吗
论文“A Review of Safe Reinforcement Learning: Methods, Theory and Applications”里是这么给出定义的
![image](https://github.com/opendilab/DI-engine-docs/assets/73453791/297c4ca7-06ca-4ee8-a7bd-cf037c8b9e9f)

2023-10-17 11:01 UTC, PaParaZz1 requested changes

2023-10-18 02:18 UTC, AltmanD commented on source/02_algo/safe_rl_zh.rst
> +原问题（Primal）
表格里对应的是 primal，和上一个小节的原问题对偶化（primal dual）是强关联

2023-10-18 10:41 UTC, PaParaZz1 approved these changes

2023-10-18 10:42 UTC, merged