Wyh env doc
opendilab/DI-engine-docs pull request #26
Opened 2021-11-04 12:27 UTC by Weiyuhong-1998

Procgen SMAC env doc

2021-11-14 16:01 UTC, MeinaPan commented on source/env_tutorial/procgen_zh.rst
> +，Miner，Jumper，Leaper，Maze，BigFish，Heist，Climber，Plunder，Ninja和BossFight）,它可以用来衡量模型学习通用技能的速度。下图所示为其中的Coinrun游戏。
它可以用来衡量模型学习通用技能的速度，从而实现/达成xxx样效果or目的

2021-11-14 16:03 UTC, MeinaPan commented on source/env_tutorial/procgen_zh.rst
> +安装gym和gym[procgen]两个库即可，可以通过pip一键安装或结合DI-engine安装
可以通过pip一键安装或结合DI-engine安装，只需要安装gym和gym[procgen]两个库即可完成

2021-11-14 16:05 UTC, MeinaPan commented on source/env_tutorial/smac_zh.rst
> +DI-engine准备好了配备有框架本身和Atari环境的镜像，可通过\ ``docker pull opendilab/ding:nightly-smac``\ 获取，或访问\ `docker
DI-engine的镜像配备有框架本身和Atari环境

2021-11-30 09:30 UTC, PaParaZz1 requested changes

2021-11-30 09:30 UTC, PaParaZz1 commented on source/env_tutorial/procgen_zh.rst
> +.. image:: ./images/coinrun.gif
介绍下不同level的coinrun的区别，可以用无序列表的形式

2021-11-30 09:30 UTC, PaParaZz1 commented on source/env_tutorial/procgen_zh.rst
> +           on_policy=False,
我们目前所有的config都要去掉`on_policy`字段

2021-11-30 09:30 UTC, PaParaZz1 commented on source/env_tutorial/procgen_zh.rst
> +               action_shape=15,
不是说coinrun的动作是5维吗，这里怎么变成15了

2021-12-08 08:11 UTC, PaParaZz1 approved these changes

2021-12-08 08:13 UTC, merged