translation(zc): add dt algorithm
opendilab/DI-engine-docs pull request #264
Opened 2023-11-27 08:15 UTC by Super1ce

add dt algorithm documentation

2023-12-13 08:55 UTC, puyuan1996 requested changes

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/diffusion.rst
> +EDAC
为什么是EDAC，应该是Planning with Diffusion for Flexible Behavior Synthesis吧

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/diffusion.rst
> +The default config is defined as follows:
多了一行

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/diffusion.rst
> +The network interface QMIX used is defined as follows:
为什么是QMIX

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/diffusion.rst
> +.. list-table:: Benchmark and comparison of DT algorithm
不是DT吧

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/diffusion.rst
> +2. Diffusion use diffuser model generating trajectory
句号，关键点写详细一点？

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/dt.rst
> +^^^^^^^
写全称加缩写吧

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/dt.rst
> +- Zheng, Q., Zhang, A., & Grover, A. (2022, June). Online decision transformer. In international conference on machine learning (pp. 27042-27059). PMLR.
这是Online decision transformer，参考文献应该是decision transformer的吧

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/diffusion.rst
> +     - .. image:: images/benchmark/pd_half_m_benchmark.png
不需要画成阴影图曲线的形式吗

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/diffusion.rst
> +EDAC
PR的名称改一下，应该是增加DT和 Diffuser的文档才对吧

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/dt.rst
> +
[1] [2] [3] 的引用没有加，文字用GPT4润色一下

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/dt.rst
> +Consequently, in 2021, a series of works represented by Decision Transformer[3]/Trajectory Transformer[1-2] Transformer emerged. These works aimed to simplify decision-making problems into sequence p
Transformer[1-2] Transformer ？

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/dt.rst
> +
这里主要是研究背景的介绍，对于DT的介绍过少了

2023-12-13 08:55 UTC, puyuan1996 commented on source/12_policies/diffusion.rst
> + :math:`T`. Diffusion, as proposed in the study `Planning with Diffusion for Flexible Behavior Synthesis <https://arxiv.org/pdf/2205.09991.pdf>`_, represents a research approach that generates trajec
这里主要是研究背景的介绍，对于 Diffuser 的介绍过少了。

2023-12-27 11:48 UTC, PaParaZz1 requested changes

2023-12-27 11:48 UTC, PaParaZz1 commented on source/12_policies/dt_zh.rst
>  ^^^^^^^
下面这个符号要比上面的文字长

2023-12-27 11:48 UTC, PaParaZz1 commented on source/12_policies/dt.rst
> +Consequently, in 2021, a series of works represented by Decision Transformer[3]/Trajectory Transformer[1-2] Transformer emerged. These works aimed to simplify decision-making problems into sequence p
模型架构不要用structure而是architecture吧

2023-12-27 11:48 UTC, PaParaZz1 commented on source/12_policies/dt.rst
> +Consequently, in 2021, a series of works represented by Decision Transformer[3]/Trajectory Transformer[1-2] Transformer emerged. These works aimed to simplify decision-making problems into sequence p
expected reward 应该是 return-to-go 吧

2023-12-28 05:41 UTC, PaParaZz1 approved these changes

2023-12-28 05:41 UTC, merged