doc(zjow): Add system design doc for agent
opendilab/DI-engine-docs pull request #265
Opened 2023-12-13 08:37 UTC by zjowowen

Add system design doc for DI-engine RL agent.

2023-12-26 08:56 UTC, PaParaZz1 requested changes

2023-12-26 08:56 UTC, PaParaZz1 commented on source/03_system/agent_zh.rst
> +RL Agent类支持包括Gym Atari和Mujoco在内的一系列经典RL基准环境，确保了类对于这些多样环境的兼容性。
MuJoCo

2023-12-26 08:56 UTC, PaParaZz1 commented on source/03_system/agent_zh.rst
> +DI-engine的RL Agent类，顾名思义，是用于RL训练或评估过程中与环境进行直接交互的智能体。
英文前后空格

2023-12-26 08:56 UTC, PaParaZz1 commented on source/03_system/agent_zh.rst
> +它包括四个主要方法："train"、"deploy"、"batch_evaluate"和"collect_data"。这让四种不同的DI-engine管线合并为一个包含四个方法的类。这避免了之前需要在不同的文件中编写个别流水线代码的需求。
``train``

2023-12-26 11:17 UTC, zjowowen commented on source/03_system/agent_zh.rst
> +RL Agent类支持包括Gym Atari和Mujoco在内的一系列经典RL基准环境，确保了类对于这些多样环境的兼容性。
fixed.

2023-12-26 11:17 UTC, zjowowen commented on source/03_system/agent_zh.rst
> +DI-engine的RL Agent类，顾名思义，是用于RL训练或评估过程中与环境进行直接交互的智能体。
fixed.

2023-12-26 11:17 UTC, zjowowen commented on source/03_system/agent_zh.rst
> +它包括四个主要方法："train"、"deploy"、"batch_evaluate"和"collect_data"。这让四种不同的DI-engine管线合并为一个包含四个方法的类。这避免了之前需要在不同的文件中编写个别流水线代码的需求。
fixed.

2023-12-27 06:54 UTC, PaParaZz1 approved these changes

2023-12-27 06:54 UTC, merged