doc(zjow): add qgpo policy documents
opendilab/DI-engine-docs pull request #267
Opened 2024-01-04 14:26 UTC by zjowowen

2024-01-15 06:06 UTC, Cloud-Pku commented on source/12_policies/qgpo.rst
> +In the paper, a novel training objective was introduced for the energy-based conditional diffusion model, which is referred to as contrastive energy prediction (CEP). CEP is a contrastive learning ob
state-action pairings or state-action pairs?

2024-01-27 10:19 UTC, PaParaZz1 requested changes

2024-01-27 10:19 UTC, PaParaZz1 commented on source/12_policies/qgpo_zh.rst
> +Q函数引导的策略优化算法，即 Q-Guided Policy Optimization(QGPO), 由路橙、陈华玉等，发表于 2023 年的论文 `《Contrastive Energy Prediction for Exact Energy-Guided Diffusion Sampling in Offline Reinforcement Learning》 <https://arxiv.
语句稍微美化下？比如：是由路橙、陈华玉等等作者在论文 xxx 中提出

2024-01-27 10:19 UTC, PaParaZz1 commented on source/12_policies/qgpo_zh.rst
> +QGPO 算法由三个关键部分组成：无条件扩散模型的行为策略、动作状态价值模型，以及扩散中间态的能量模型，它用于引导最优策略的条件扩散模型的生成。
关键部分的这三点可以加粗

2024-01-27 10:19 UTC, PaParaZz1 commented on source/12_policies/qgpo_zh.rst
> +通过使用离线数据集训练扩散模型，可以得到无条件扩散模型。而使用基于贝尔曼方程的训练目标，可以得到动作状态价值模型。
三个模块之间的关系好像说的不太清晰？

2024-01-27 10:19 UTC, PaParaZz1 commented on source/12_policies/qgpo_zh.rst
> +它可被视为以 :math:`-Q_{\psi}(s,a)` 为能量函数， :math:`\beta` 为温度系数，关于动作 :math:`a` 的Boltzmann 分布。
Boltzmann 左边的空格

2024-01-27 10:19 UTC, PaParaZz1 commented on source/12_policies/qgpo_zh.rst
> +强化学习算法中的约束策略优化的最优策略 :math:`\pi^*` 满足：
约束策略优化的最优策略，有点没明白

2024-01-27 10:19 UTC, PaParaZz1 commented on source/12_policies/qgpo_zh.rst
> +| 环境                |最优平均回报      | 评估结果                                             | 配置链接                  | 对比                 |
这个表编译的结果应该不正常，检查一下，另外表的写法可以参考C51中那种，比较简单

2024-01-27 10:19 UTC, PaParaZz1 commented on source/12_policies/qgpo_zh.rst
> +其中 :math:`\phi` 是能量指导函数的参数。
讲一下最终训练完成后，action 怎么获得吧，以及这样设计的好处

2024-01-27 12:13 UTC, zjowowen commented on source/12_policies/qgpo_zh.rst
> +Q函数引导的策略优化算法，即 Q-Guided Policy Optimization(QGPO), 由路橙、陈华玉等，发表于 2023 年的论文 `《Contrastive Energy Prediction for Exact Energy-Guided Diffusion Sampling in Offline Reinforcement Learning》 <https://arxiv.
fixed.

2024-01-27 12:22 UTC, zjowowen commented on source/12_policies/qgpo_zh.rst
> +QGPO 算法由三个关键部分组成：无条件扩散模型的行为策略、动作状态价值模型，以及扩散中间态的能量模型，它用于引导最优策略的条件扩散模型的生成。
fixed.

2024-01-27 12:22 UTC, zjowowen commented on source/12_policies/qgpo_zh.rst
> +通过使用离线数据集训练扩散模型，可以得到无条件扩散模型。而使用基于贝尔曼方程的训练目标，可以得到动作状态价值模型。
fixed.

2024-01-27 12:23 UTC, zjowowen commented on source/12_policies/qgpo_zh.rst
> +它可被视为以 :math:`-Q_{\psi}(s,a)` 为能量函数， :math:`\beta` 为温度系数，关于动作 :math:`a` 的Boltzmann 分布。
fixed.

2024-01-27 12:23 UTC, zjowowen commented on source/12_policies/qgpo_zh.rst
> +强化学习算法中的约束策略优化的最优策略 :math:`\pi^*` 满足：
fixed.

2024-01-27 12:23 UTC, zjowowen commented on source/12_policies/qgpo_zh.rst
> +| 环境                |最优平均回报      | 评估结果                                             | 配置链接                  | 对比                 |
fixed.

2024-01-27 12:23 UTC, zjowowen commented on source/12_policies/qgpo_zh.rst
> +其中 :math:`\phi` 是能量指导函数的参数。
fixed.

2024-01-28 15:39 UTC, PaParaZz1 approved these changes

2024-01-28 15:39 UTC, merged