feature(zlx): competitive_rl env tutorial
opendilab/DI-engine-docs pull request #27
Opened 2021-11-05 03:18 UTC by LuciusMos

2021-11-14 15:38 UTC, MeinaPan commented on source/env_tutorial/competitive_rl_zh.rst
> +Competitive RL 是由香港中文大学（CUHK）开发的一个对抗性游戏环境，环境中允许两个玩家分别控制双方进行对抗。链接为 `github repo <https://github.com/cuhkrlcourse/competitive-rl>`_
可以在加些描述性的话，这个对抗性游戏环境具有什么特点，以及“环境中允许两个玩家分别控制双方进行对抗”需要达到什么样的目的

2021-11-14 15:46 UTC, MeinaPan commented on source/env_tutorial/competitive_rl_zh.rst
> +   - Competitive Pong (cPong): 是将 Atari 中的 Pong 修改为对抗式的环境，即允许对抗的双方均为用户操控，均可为可训练的智能体。
即允许对抗的双方均为“用户”（可改为如玩家）操控，且均都是可被训练的智能体agent

2021-11-14 15:58 UTC, MeinaPan commented on source/env_tutorial/competitive_rl_zh.rst
> +-  虽然对战有双方，但是由于双方的奖励之和必定为0，故只返回 **左侧玩家** 的奖励。
【奖励代表。。。】这句话可以挪到【虽然对战有双方的前面】

2021-11-15 05:47 UTC, LuciusMos commented on source/env_tutorial/competitive_rl_zh.rst
> +Competitive RL 是由香港中文大学（CUHK）开发的一个对抗性游戏环境，环境中允许两个玩家分别控制双方进行对抗。链接为 `github repo <https://github.com/cuhkrlcourse/competitive-rl>`_
已修改

2021-11-15 05:47 UTC, LuciusMos commented on source/env_tutorial/competitive_rl_zh.rst
> +   - Competitive Pong (cPong): 是将 Atari 中的 Pong 修改为对抗式的环境，即允许对抗的双方均为用户操控，均可为可训练的智能体。
已修改

2021-11-15 05:47 UTC, LuciusMos commented on source/env_tutorial/competitive_rl_zh.rst
> +-  虽然对战有双方，但是由于双方的奖励之和必定为0，故只返回 **左侧玩家** 的奖励。
已修改

2021-12-09 12:00 UTC, LikeJulia commented on source/env_tutorial/competitive_rl_zh.rst
> +   - Competitive Car-Racing (cCarRacing): 赛车环境允许两辆车在同一个赛道地图中进行竞速。
根据技术文档规范，智能体统称为agent 即可。

2021-12-09 14:33 UTC, PaParaZz1 requested changes

2021-12-09 14:33 UTC, PaParaZz1 commented on source/env_tutorial/competitive_rl_zh.rst
> +    pong_double_env = gym.make("cPongDouble-v0")
解释一下带Double的环境的含义

2021-12-09 14:33 UTC, PaParaZz1 commented on source/env_tutorial/competitive_rl_zh.rst
> +-  基本无变换，但允许传回的双方动作为堆叠的 ``torch.Tensor`` 或 ``np.ndarry`` 或 ``list``
env里面不能为tensor了

2021-12-09 14:33 UTC, PaParaZz1 commented on source/env_tutorial/competitive_rl_zh.rst
> +    racing_double_env = gym.make("cCarRacingDouble-v0")
还是简单再运行一步

2021-12-13 06:14 UTC, LuciusMos commented on source/env_tutorial/competitive_rl_zh.rst
> +    racing_double_env = gym.make("cCarRacingDouble-v0")
已修改

2021-12-13 06:14 UTC, LuciusMos commented on source/env_tutorial/competitive_rl_zh.rst
> +-  基本无变换，但允许传回的双方动作为堆叠的 ``torch.Tensor`` 或 ``np.ndarry`` 或 ``list``
已修改

2021-12-13 06:15 UTC, LuciusMos commented on source/env_tutorial/competitive_rl_zh.rst
> +    pong_double_env = gym.make("cPongDouble-v0")
已修改，解释在概述部分

2021-12-13 06:15 UTC, LuciusMos commented on source/env_tutorial/competitive_rl_zh.rst
> +   - Competitive Car-Racing (cCarRacing): 赛车环境允许两辆车在同一个赛道地图中进行竞速。
已修改

2021-12-14 08:09 UTC, merged