doc(rjy): add doc for ising model env
opendilab/DI-engine-docs pull request #271
Opened 2024-03-29 06:33 UTC by nighood

2024-04-10 03:52 UTC, PaParaZz1 requested changes

2024-04-10 03:52 UTC, PaParaZz1 commented on source/13_envs/ising_model_zh.rst
> +Ising Model
add this file into `index_zh.rst`

2024-04-10 03:52 UTC, PaParaZz1 commented on source/13_envs/ising_model_zh.rst
> +伊辛模型是一种经典的物理模型，用于描述铁磁性材料的微观磁态。在本环境中，该模型被扩展为一个多智能体系统，每个智能体通过局部交互影响整体系统的磁态。智能体的目标是通过改变自身的自旋状态来优化整个系统的有序性。
带上英文原词？

2024-04-10 03:52 UTC, PaParaZz1 commented on source/13_envs/ising_model_zh.rst
> +- 当全局序参数order_param达到1时，表示系统已经达到完全有序的状态，此时认为环境任务完成，游戏结束。序参数是系统自旋向上和自旋向下的智能体数量差的绝对值，除以总智能体数量。
英文两边空格

2024-04-10 03:52 UTC, PaParaZz1 commented on source/13_envs/ising_model_zh.rst
> +-  待补充
把最新的实验图放上来？

2024-04-10 08:45 UTC, Cloud-Pku commented on source/13_envs/ising_model_zh.rst
> +Mean field 近似是一种数学和统计物理中的方法，用于近似描述大量相互作用粒子的系统。在这种近似中，每个粒子被假设只受到其他所有粒子的平均效应的影响，而不是受到每个单独粒子的影响。这种方法可以简化复杂系统的计算，使得分析和优化变得更加可行。
加个引用？

2024-04-10 08:45 UTC, Cloud-Pku commented on source/13_envs/ising_model_zh.rst
> +    reward = - 0.5 * global_state[agent.state.p_pos] * np.sum(global_state.flatten() * agent.spin_mask)
这里邻居自旋平均值计算为啥不需要除以邻居数量

2024-04-17 06:26 UTC, nighood commented on source/13_envs/ising_model_zh.rst
> +    reward = - 0.5 * global_state[agent.state.p_pos] * np.sum(global_state.flatten() * agent.spin_mask)
应该是因为所有的智能体的视野大小是统一的，邻居数量相同，所以这里没有除以邻居数量

2024-04-17 07:21 UTC, PaParaZz1 approved these changes

2024-04-17 07:21 UTC, merged