doc(jrn): add multi-agent particle env tutorial chinese
opendilab/DI-engine-docs pull request #42
Opened 2021-11-18 15:37 UTC by jiaruonan

Add multi-agent particle env tutorial chinese.
Thank Zhenjie for his cherry-pick help.

2021-11-30 10:02 UTC, PaParaZz1 requested changes

2021-11-30 10:02 UTC, PaParaZz1 commented on source/env_tutorial/multiagent_particle.rst
> +-  当游戏运行至\ ``max_cycles``\ 即为游戏结束，MPE 源码默认子环境\ ``max_cycles=25``\ 。
这个cycle的含义是？不是执行的步数吧

2021-11-30 10:02 UTC, PaParaZz1 commented on source/env_tutorial/multiagent_particle.rst
> +注：对于某些特殊的算法，比如QMIX，需要使用专门的入口函数，示例可以参考 `link <https://github.com/opendilab/DI-engine/blob/main/dizoo/multiagent_particle/config/modified_predator_prey_qmix_config.py>`__.
qmix并没有用特殊的入口函数呀

2021-12-09 14:15 UTC, jiaruonan commented on source/env_tutorial/multiagent_particle.rst
> +   rew_space = gym.spaces.Box(low=-inf, high=inf, shape=(1, ), dtype=np.float32)
通过查看原始MPE的Simple Tag环境reward_range，发现它的范围设置也为(-inf, inf)，所以不用修改此处的reward设定。

2021-12-10 08:21 UTC, jiaruonan commented on source/env_tutorial/multiagent_particle.rst
> +MPE 作为 NIPS2017 那篇著名的多智能体强化学习算法 MADDPG 的实验环境，因而被人们广泛所知。
文档内容已修改。

2021-12-12 14:21 UTC, merged