add diayn.zh doc
opendilab/DI-engine-docs pull request #43
Opened 2021-11-18 17:24 UTC by Will-Nie

Add zh doc for the algorithm diversity is all you need

2021-11-30 09:02 UTC, puyuan1996 commented on source/hands_on/diayn.rst
> +DIAYN的接口定义如下,它相对于SAC主要有加入了判别器的训练流程及奖励函数的修改
DIAYN的接口定义如下, 相对于SAC，主要区别在：加入了判别器的训练流程，修改了奖励函数。

2021-11-30 09:02 UTC, puyuan1996 commented on source/hands_on/diayn.rst
> +Note: ``...`` indicates the omitted code snippet. For the complete code, please refer to our
这块用中文吧，我也写错了:)

2021-11-30 09:02 UTC, puyuan1996 commented on source/hands_on/diayn.rst
> +在收集数据时，我们会在每个episode前通过均匀分布采样一个技能
在收集数据时，我们会在每个episode开始前，通过均匀分布，随机采样出一个技能：

2021-11-30 09:03 UTC, puyuan1996 commented on source/hands_on/diayn.rst
> +我们编写的判别器网络是由 ``linear encoder`` + ``regression head`` 构成
字体格式不对，需要空出一行。

2021-12-03 07:34 UTC, PaParaZz1 requested changes

2021-12-03 07:34 UTC, PaParaZz1 commented on source/hands_on/diayn.rst
> +DIAYN
中文文档的话，以zh.rst结尾，即`diayn_zh.rst`

2021-12-03 07:34 UTC, PaParaZz1 commented on source/hands_on/diayn.rst
> +3. 用于模仿学习：用学到的技能去模仿专家
不通顺吧，应该是把学到的技能作为要模仿的专家行为？

2021-12-03 07:34 UTC, PaParaZz1 commented on source/hands_on/diayn.rst
> +   .. image:: ./images/ezgif.com-gif-maker4.gif
讲一下不同skill具体的含义吧，更易懂

2021-12-03 18:41 UTC, Will-Nie commented on source/hands_on/diayn.rst
> +DIAYN
感谢！已修改！

2021-12-03 18:42 UTC, Will-Nie commented on source/hands_on/diayn.rst
> +   .. image:: ./images/ezgif.com-gif-maker4.gif
好嘞！我加一波

2021-12-03 18:49 UTC, Will-Nie commented on source/hands_on/diayn.rst
> +该算法可以使智能体在没有奖励的环境中能够自我学习产生奖励函数, 并且自动探索出来一些有用的技能（skills）。这些学到的技能为很多RL任务提供了基石，例如，要找到一个能在任务中获得高回报的策略，通常只需选择具有最大回报的技能就足够了。
感谢！ 已修改

2021-12-03 18:50 UTC, Will-Nie commented on source/hands_on/diayn.rst
> +3. 用于模仿学习：用学到的技能去模仿专家
感谢， 已修改！

2021-12-03 18:51 UTC, Will-Nie commented on source/hands_on/diayn.rst
> +我们编写的判别器网络是由 ``linear encoder`` + ``regression head`` 构成
感谢， 已修改

2021-12-03 19:00 UTC, Will-Nie commented on source/hands_on/diayn.rst
> +由于我们无法对所有的状态和技能进行整合以准确计算p(z \| s)，我们用一个学习到的判别器q(z \| s)来近似这个后验。詹森不等式(Jensen’s Inequality) 告诉我们，用q(z \| s)代替p(z | s)可以给我们的目标F(θ)提供一个变分下限G(θ, φ)
我试了一下，这样改好像会报错

2021-12-03 19:09 UTC, Will-Nie commented on source/hands_on/diayn.rst
> +第一项鼓励我们对p(z)的先验分布具有很高的熵。在我们的方法中，我们把p(z)固定为均匀分布，保证它具有最大的熵。第二项表明，从当前状态推断技能z应该是很容易的。第三项表明，每个技能应该尽可能地随机行动，这一点我们通过使用最大熵策略来代表每个技能来实现。
没问题， 感谢感谢！

2021-12-03 19:46 UTC, Will-Nie commented on source/hands_on/diayn.rst
> +3. 用于模仿学习：用学到的技能去模仿专家
感谢！这里应该是 找到最像专家行为的技能, 并把该技能对应的策略作为模仿学习中学到的策略

2022-05-11 08:17 UTC, PaParaZz1 commented
This PR has been integrated in #135

2022-05-11 08:17 UTC, closed without merging