doc(pu): add r2d3 doc_zh
opendilab/DI-engine-docs pull request #45
Opened 2021-11-19 14:33 UTC by puyuan1996

2021-11-26 11:58 UTC, Will-Nie commented on source/hands_on/r2d3_zh.rst
> +4. 预训练，在智能体与环境交互之前，我们可以先利用专家演示样本训练Q网络，期望能得到一个好的初始参数，加速后续的训练进程。
Do we have demo codes for this part?

2021-11-28 10:56 UTC, puyuan1996 commented on source/hands_on/r2d3_zh.rst
> +4. 预训练，在智能体与环境交互之前，我们可以先利用专家演示样本训练Q网络，期望能得到一个好的初始参数，加速后续的训练进程。
预训练的demo codes吗？是在config里面直接设置per_train_iter_k这个参数实现的

2021-12-01 04:35 UTC, puyuan1996 commented on source/hands_on/r2d3_zh.rst
> +4. 预训练，在智能体与环境交互之前，我们可以先利用专家演示样本训练Q网络，期望能得到一个好的初始参数，加速后续的训练进程。
哦哦好的，谢谢啦

2021-12-06 06:59 UTC, PaParaZz1 requested changes

2021-12-06 06:59 UTC, PaParaZz1 commented on source/hands_on/index.rst
> +    r2d3
加上zh吧，r2d3_zh

2021-12-06 06:59 UTC, PaParaZz1 commented on source/hands_on/r2d3_zh.rst
> +5.r2d3e的提出是为了解决初始条件高度可变、部分可观察环境中的困难探索问题，其他探索相关的论文，读者可以参考 `NGU <https://arxiv.org/abs/2002.06038>`_ ，它是融合了
多了一个e

2021-12-06 06:59 UTC, PaParaZz1 commented on source/hands_on/r2d3_zh.rst
> +演示和智能体经验验之间的比率是一个关键的超参数, 必须仔细调整以实现良好的性能。
多了一个验

2021-12-06 06:59 UTC, PaParaZz1 commented on source/hands_on/r2d3_zh.rst
> +下面描述r2d3的损失函数设置，和DQfD一样，不过这里所有的Q值都是通过上面所述的循环神经网络结构计算得到。
用无序列表或有序列表

2021-12-06 06:59 UTC, PaParaZz1 commented on source/hands_on/r2d3_zh.rst
> +1. 训练所用的minibatch中有pho的概率为专家演示轨迹。其具体实现方式如下，通过从batch_size大小个的[0，1]均匀分分布中采样，如果采样值大于pho则选择一个专家演示轨迹
多了一个分

2021-12-08 07:51 UTC, PaParaZz1 approved these changes

2021-12-08 07:51 UTC, merged