feature(zlx): best practice(zh)-how to implement an env in di-engine
opendilab/DI-engine-docs pull request #57
Opened 2021-12-15 09:16 UTC by LuciusMos

2021-12-16 08:35 UTC, PaParaZz1 requested changes

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +虽然已经在 ``DI-zoo`` 中提供了大量的强化学习常用环境，但用户还是会需要将自己的环境迁移到 ``DI-engine`` 中。因此在本节中，将会介绍如何一步步进行上述迁移，以满足 ``BaseEnv`` 的规范，从而轻松应用在训练的 pipeline 中。
这里贴一下链接吧，链接到readme那个环境表格

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +虽然已经在 ``DI-zoo`` 中提供了大量的强化学习常用环境，但用户还是会需要将自己的环境迁移到 ``DI-engine`` 中。因此在本节中，将会介绍如何一步步进行上述迁移，以满足 ``BaseEnv`` 的规范，从而轻松应用在训练的 pipeline 中。
以满足`DI-engine`的基础环境基类`BaseEnv`的规范

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +下面的介绍将分为 **基础** 和 **进阶** 两部分。
最开始讲一下基础和进阶的含义吧，比如基础是跑通所必须的，进阶是使用其他功能

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +如果要在 DI-engine 中使用环境，需要实现一个继承自 ``BaseEnv`` 的子类环境，例如 ``YourEnv`` 。 ``YourEnv`` 和你自己的环境之间是聚合关系，即在一个 ``YourEnv`` 实例中，会持有一个你自己的环境的实例。
聚合关系给个百科链接，避免不懂OOP的人

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +强化学习的环境有一些主要的、普遍被大多数环境实现的接口，如 ``reset()``, ``step()``, ``seed()`` 等。在 DI-engine 中， ``BaseEnv`` 将对这些接口进行进一步的封装，下面大部分情况下将以 Atari 为例进行说明。(in ``dizoo/atari/envs/atari_env.py`` 和 ``dizoo/atari/envs/atari_
写成：具体代码可以参见 [AtariEnv](https://github.com/opendilab/DI-engine/blob/main/dizoo/atari/envs/atari_env.py)

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +   ``reset`` 方法中会根据 ``self._init_flag`` 判断是否需要实例化实际环境，并进行随机种子的设置（将在3中详细讲解），然后调用原始环境的 ``reset`` 方法得到初始状态下的观测值，并转换为 ``np.ndarray`` 数据格式（将在5中详细讲解），并初始化 ``self._final_eval_reward`` 的值（将在4中详细讲解），在 Atari 中
说下`self._final_eval_reward`的定义吧：环境一个episode所获得的累积真实奖励和，用于评价智能体在该环境上的性能，不用于训练。

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +   **动态种子** 用于训练环境，尽量使得每个 episode 的随机种子都不相同，它们都在 ``reset`` 方法中由一个随机数发生器 ``100 * np.random.randint(1, 1000)`` 产生（但这个随机数发生器的种子是通过环境的 ``seed`` 方法固定的）。需要在 ``seed`` 方法中不传入 ``dynamic_seed`` 参数，或者传入参数为 ``Tr
但这个随机数发生器的种子是通过环境的 ``seed`` 方法固定的，因此能保证实验的可复现性

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +      -  ``step`` 方法返回的 ``reward``，此处还要求 ``reward`` 必须为 **一维** ，而不能是零维，例如 Atari 中的代码 ``rew = to_ndarray([rew])``
还要求done必须是bool类型，不能是np.bool

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +1. 环境预处理wrapper
讲一下wrapper的定义和意义吧，比如给个传送门https://en.wikipedia.org/wiki/Wrapper_function，当然最好找个中文

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +      - ``MaxAndSkipEnv``: 跳着返回几帧中的最大值，可认为是时间步上的一种 max pooling
跳着这个翻译去掉吧

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +      - ``WarpFrame``: 将原始的图像画面利用 ``cv2`` 库的 ``cvtColor`` 转换为一定长宽的图像（一般为 84x84）
cvtColor是转变颜色编码，转换长宽是resize

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +      - ``FrameStack``: 将一定数量（一般为4）的 frame 堆叠在一起，作为新的 observation
用于处理POMDP的情况，比如单帧信息无法知道运动的速度方向

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +   在 ``EnvManager`` 中，如果想使用 ``shared_memory`` 技术加快环境返回的大型矢量数据的传输速度，就需要在环境的 ``info`` 方法中给出 ``obs`` ``action`` ``reward`` 等数据的 **shape** 和 **dtype** 。
矢量改成张量吧

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +   在 ``EnvManager`` 中，如果想使用 ``shared_memory`` 技术加快环境返回的大型矢量数据的传输速度，就需要在环境的 ``info`` 方法中给出 ``obs`` ``action`` ``reward`` 等数据的 **shape** 和 **dtype** 。
以及根据环境的维度自动创建神经网络功能

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +   其中， ``updatet_shape`` 函数如下：
typo

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +   如果想对游戏视频进行保存，那么就需要实现 ``enable_save_replay`` 方法。在该方法中指定录像存储的路径，并利用 ``gym`` 提供的装饰器封装环境，如代码所示：
讲一下我们并没有强制要求实现render方法，而是通过存游戏视频（replay）的方式来可视化

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +
讲一下这两个方法在具体使用时的例子？可以参考serial_pipeline最开头的部分

2021-12-16 08:35 UTC, PaParaZz1 commented on source/best_practice/ding_env_zh.rst
> +
后面补一下QA环节吧：
1. MARL环境如何处理，以cpong为例
2. 混合动作空间如何处理，以gym_hybrid为例

2021-12-16 09:31 UTC, LuciusMos commented on source/best_practice/ding_env_zh.rst
> +虽然已经在 ``DI-zoo`` 中提供了大量的强化学习常用环境，但用户还是会需要将自己的环境迁移到 ``DI-engine`` 中。因此在本节中，将会介绍如何一步步进行上述迁移，以满足 ``BaseEnv`` 的规范，从而轻松应用在训练的 pipeline 中。
已修改

2021-12-16 09:31 UTC, LuciusMos commented on source/best_practice/ding_env_zh.rst
> +虽然已经在 ``DI-zoo`` 中提供了大量的强化学习常用环境，但用户还是会需要将自己的环境迁移到 ``DI-engine`` 中。因此在本节中，将会介绍如何一步步进行上述迁移，以满足 ``BaseEnv`` 的规范，从而轻松应用在训练的 pipeline 中。
已修改

2021-12-16 09:31 UTC, LuciusMos commented on source/best_practice/ding_env_zh.rst
> +下面的介绍将分为 **基础** 和 **进阶** 两部分。
已修改

2021-12-16 09:31 UTC, LuciusMos commented on source/best_practice/ding_env_zh.rst
> +如果要在 DI-engine 中使用环境，需要实现一个继承自 ``BaseEnv`` 的子类环境，例如 ``YourEnv`` 。 ``YourEnv`` 和你自己的环境之间是聚合关系，即在一个 ``YourEnv`` 实例中，会持有一个你自己的环境的实例。
已修改

2021-12-16 09:31 UTC, LuciusMos commented on source/best_practice/ding_env_zh.rst
> +强化学习的环境有一些主要的、普遍被大多数环境实现的接口，如 ``reset()``, ``step()``, ``seed()`` 等。在 DI-engine 中， ``BaseEnv`` 将对这些接口进行进一步的封装，下面大部分情况下将以 Atari 为例进行说明。(in ``dizoo/atari/envs/atari_env.py`` 和 ``dizoo/atari/envs/atari_
已修改

2021-12-17 12:36 UTC, chenyingvivian commented on source/best_practice/ding_env_zh.rst
> +   如果想对游戏视频进行保存，那么就需要实现 ``enable_save_replay`` 方法。在该方法中指定录像存储的路径，并利用 ``gym`` 提供的装饰器封装环境，如代码所示：
“实现”改成“使用”

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
> +虽然已经在 ``DI-zoo`` 中提供了大量的强化学习常用环境（ `简明表格链接 <https://github.com/opendilab/DI-engine#environment-versatility>`_ ），但用户还是会需要将自己的环境迁移到 ``DI-engine`` 中。因此在本节中，将会介绍如何一步步进行上述迁移，以满足 ``DI-engine`` 的基础环境基类 ``Bas
（ `已支持的环境 <https://github.com/opendilab/DI-engine#environment-versatility>`_ ）

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
> +强化学习的环境有一些主要的、普遍被大多数环境实现的接口，如 ``reset()``, ``step()``, ``seed()`` 等。在 DI-engine 中， ``BaseEnv`` 将对这些接口进行进一步的封装，下面大部分情况下将以 Atari 为例进行说明。具体代码可以参考 `Atari Env <https://github.com/opendilab/DI-engine/blob/
强化学习的环境有一些普遍能被大多数环境实现的主要接口，

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
>     以 Atari 为例。``__init__`` 中不实例化环境，只是设置配置项 ``self._cfg`` ，以及初始化变量 ``self._init_flag`` 用于记录是否是第一次调用 ``reset`` 方法（即环境是否还没有被初始化）。
以 Atari 为例。``__init__`` 并不实例化环境，只是设置配置项 ``self._cfg`` ，以及初始化变量 ``self._init_flag`` 用于记录是否是第一次调用 ``reset`` 方法（即环境是否还没有被初始化）。

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
> +   **静态种子** 用于测试环境，保证每个 episode 的随机种子相同，即 ``reset`` 时只会采用 ``self._seed`` 这个固定的静态种子数值需要在。需要 ``seed`` 方法中手动传入 ``dynamic_seed`` 参数为 ``False`` 。
这个固定的静态种子数值需要在。需要 ``seed`` 方法中手动传入 ``dynamic_seed`` 参数为 ``False`` 。

这个是 书写错误？   “需要在。需要”
应该是 ：
  **静态种子** 用于测试环境，保证每个 episode 的随机种子相同，即 ``reset`` 时只会采用 ``self._seed`` 这个固定的静态种子数值。需要在 ``seed`` 方法中手动传入 ``dynamic_seed`` 参数为 ``False`` 。

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
> +   在 1. 中已经介绍了 DI-engine 的 **Lazy Init** 初始化方式，在第一次调用 ``reset`` 方法时，进行实际的环境初始化。
与line59的格式一致    采用其中一种，例如：“在1.中”  “在1中” “在`` __init__ ``中”

如何在第一次调用 ``reset`` 方法时，进行实际的环境初始化。

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
最终，将上述四个数据放入一个 ``BaseEnvTimestep`` 中将定义为一个 ``namedtuple`` 并返回： ``BaseEnvTimestep = namedtuple('BaseEnvTimestep', ['obs', 'reward', 'done', 'info'])``

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
（ ``done == True `` ），那么就添加到 ``info``
这段在view的时候会出现错误，没办法截图，不太清楚的话可以企业微信联系我（hs）

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
>     但是，在其他的环境中，可能需要的不是一个 episode 的 reward 之和。例如，在 smac 中，需要当前 episode 的胜率，因此就需要在 修改第二步 ``step`` 方法中简单的累加，而是记录对局情况，最终在 episode 结束时返回计算得到的胜率。
“而是”记录对局情况
删掉而是？

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
>     如果上述 wrapper 不能满足你的需要，也可以自行实现一个。
如果上述 wrapper 不能满足你的需要，也可以自行定制wrapper。

2021-12-17 12:47 UTC, norman26625 commented on source/best_practice/ding_env_zh.rst
>  4. 训练环境和测试环境使用使用不同 config
多写了“使用”

2021-12-20 09:41 UTC, LuciusMos commented on source/best_practice/ding_env_zh.rst
> +   如果想对游戏视频进行保存，那么就需要实现 ``enable_save_replay`` 方法。在该方法中指定录像存储的路径，并利用 ``gym`` 提供的装饰器封装环境，如代码所示：
感觉此处用“实现”更准确一些，因为这个方法是用户需要自己实现的

2021-12-20 09:53 UTC, LuciusMos commented on source/best_practice/ding_env_zh.rst
>     但是，在其他的环境中，可能需要的不是一个 episode 的 reward 之和。例如，在 smac 中，需要当前 episode 的胜率，因此就需要在 修改第二步 ``step`` 方法中简单的累加，而是记录对局情况，最终在 episode 结束时返回计算得到的胜率。
修改为了：因此就需要修改第二步 ``step`` 方法中简单的累加，改为记录对局情况，并最终在 episode 结束时返回计算得到的胜率。

2021-12-21 05:44 UTC, PaParaZz1 approved these changes

2021-12-21 05:45 UTC, merged