Main zh
opendilab/DI-engine-docs pull request #75
Opened 2022-01-20 12:53 UTC by Khaiiiiiiiii

2022-02-10 10:10 UTC, PaParaZz1 requested changes

2022-02-10 10:10 UTC, PaParaZz1 commented on d4rl.rst
> +.. code::python
少了个空格，语法未生效，`.. code:: python`

2022-02-10 10:10 UTC, PaParaZz1 commented on source/env_tutorial/d4rl.rst
> +D4RL (Mujoco)
重复了，把重复的删掉，路径为`source/env_tutorial/d4rl.rst`

2022-02-10 10:10 UTC, PaParaZz1 commented on source/env_tutorial/smac.rst
> +mirror
镜像这个词用Image，并且标题首字母大写

2022-03-10 11:07 UTC, VaninaY commented on source/env_tutorial/smac.rst
> +- The game operation button space, generally a discrete action space of size N (N varies with the specific sub-environment), the data type is \ ``int``\ , you need to pass in python values ​​(or 0-di
- The game operation button space, generally a discrete action space of size N (N varies with the specific sub-environment), the data type is \ ``int``\ , you need to pass in python values ​​(or 0-dimensional np arrays, such as actions 3 is\ ``np.array(3)``\ )

2022-03-10 11:08 UTC, VaninaY commented on source/env_tutorial/smac.rst
> +- The game wins or loses, the victory is 1, and the defeat is 0, which is generally an \``int``\ value.
- The game wins or loses, the victory is 1, and the defeat is 0, which is generally an \ ``int``\  value.

2022-03-10 11:13 UTC, VaninaY commented on source/hands_on/ICM.rst
> +1. As shown in the figure on the left, the agent samples the action a in the state :math:`s_t` through the current policy :math:`\pi` and executes it, and finally obtains the state :math:`s_{t+1}`. T
1. As shown in the figure on the left, the agent samples the action a in the state :math:`s_t` through the current policy :math:`\pi` and executes it, and finally obtains the state :math:`s_{t+1}`. The total reward is the sum of two partial rewards, one part is the external reward :math:`r_t^e`, that is, the sparse reward obtained in the environment; the other part is the intrinsic reward obtained by the ICM :math:`r_t^i` (The specific calculation process is given in step 4), the final strategy needs to achieve the purpose of training by optimizing the total reward.

2022-03-10 11:16 UTC, VaninaY commented on source/hands_on/ICM.rst
> +3. The forward model of ICM will take :math:`Phi(s_t)`  and action value :math:`a_t` as input, and output the predicted value of the feature vector of the state at the next moment :math:`hat{\Phi} (s
3. The forward model of ICM will take :math:`\Phi(s_t)` and action value :math:`a_t` as input, and output the predicted value of the feature vector of the state at the next moment :math:`\hat{\Phi}(s_{t+1})` .

2022-03-10 11:18 UTC, VaninaY commented on source/hands_on/ICM.rst
> + :math:`{\min}_{\theta_F, \theta_E} L_F(\hat{\phi(s_{t+1})},\phi(s_{t+1}))`
:math:`{\min}_{\theta_F, \theta_E} L_F(\hat{\phi(s_{t+1})},\phi(s_{t+1}))`

2022-03-10 11:20 UTC, VaninaY commented on source/hands_on/ICM.rst
> +.. code-block::python
.. code-block:: python

2022-03-10 11:21 UTC, VaninaY commented on source/hands_on/ICM.rst
> +        .. code-block::python
.. code-block:: python

2022-03-10 11:25 UTC, VaninaY commented on d4rl.rst
> +1. The mujoco-py library no longer requires an activation license (``mujoco-py>=2.1.0``), you can install free-mujoco-py via \ `pip <https://github.com/openai/ mujoco-py/pull/640>`__ install
1. The mujoco-py library no longer requires an activation license (``mujoco-py>=2.1.0``), you can \ `pip install free-mujoco-py <https://github.com/openai/mujoco-py/pull/640>`__  install

2022-03-30 10:55 UTC, PaParaZz1 requested changes

2022-03-30 10:55 UTC, PaParaZz1 commented on d4rl.rst
> +D4RL (Mujoco)
modify the location of `d4rl.rst`

2022-03-30 10:55 UTC, PaParaZz1 commented on d4rl.rst
> +.. image :: ./images/d4rl.gif
polish image

2022-03-30 10:55 UTC, PaParaZz1 commented on d4rl.rst
> +--------
it should be longer than head

2022-03-30 10:55 UTC, PaParaZz1 commented on d4rl.rst
> +DI-zoo Rnnable Code Example
typo

2022-03-30 10:55 UTC, PaParaZz1 commented on source/env_tutorial/smac.rst
> +Mirror
use `Image` rather than `Mirror`

2022-05-11 08:17 UTC, closed without merging

2022-05-11 08:17 UTC, Khaiiiiiiiii commented
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2022-10-11 07:46 UTC, Khaiiiiiiiii commented
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。