doc(cy): translate env tutorial into English
opendilab/DI-engine-docs pull request #77
Opened 2022-01-22 15:52 UTC by chenyingvivian

2022-02-10 09:43 UTC, PaParaZz1 requested changes

2022-03-11 03:51 UTC, VaninaY commented on Gym_en.rst
> +- \ ``Turn (Rotation value)`` \: means to turn the agent in the direction of \ ``rotation value`` \. The value range of \ ``Rotation value`` \ is \ ``[-1,1]`` \. The numeric type is \``float32``.
- \ ``Turn (Rotation value)`` \: means to turn the agent in the direction of \ ``rotation value`` \. The value range of \ ``Rotation value`` \ is \ ``[-1,1]`` \. The numeric type is \ ``float32``.

2022-03-11 04:03 UTC, VaninaY commented on Gym_en.rst
> +.. code::python
.. code:: python

2022-03-11 04:03 UTC, VaninaY commented on Gym_en.rst
> +.. code::python
.. code:: python

2022-03-11 04:13 UTC, VaninaY commented on Gym_en.rst
> +.. code::python
.. code:: python

2022-03-11 04:13 UTC, VaninaY commented on Gym_en.rst
> +There are two built-in environments, \``"Moving-v0"``\ and \``"Sliding-v0"``\. The former does not consider conservation of inertia, while the latter does (so is more practical). The two environments
There are two built-in environments,\ ``"Moving-v0"`` \and \ ``"Sliding-v0"`` \. The former does not consider conservation of inertia, while the latter does (so is more practical). The two environments are consistent in state space, action space, and reward space.

2022-03-11 04:13 UTC, VaninaY commented on Gym_en.rst
> +The following provides a complete gym hybrid environment config, using DDPG as the baseline algorithm. Please run the \``gym_hybrid_ddpg_config.py``\ file in the \``DI-engine/dizoo/gym_hybrid``\ dire
The following provides a complete gym hybrid environment config, using DDPG as the baseline algorithm. Please run the \ ``gym_hybrid_ddpg_config.py`` \ file in the \ ``DI-engine/dizoo/gym_hybrid`` \ directory, as follows.

2022-03-11 04:13 UTC, VaninaY commented on Gym_en.rst
> +.. code::python
.. code:: python

2022-03-11 04:13 UTC, VaninaY commented on cartpole_en.rst
> +The Cartpole environment is built into the gym, and you can install the gym directly. Its environment id is \``CartPole-v0``\.
The Cartpole environment is built into the gym, and you can install the gym directly. Its environment id is \ ``CartPole-v0`` \.

2022-03-11 04:13 UTC, VaninaY commented on cartpole_en.rst
> +.. code:: shell
.. code:: shell

2022-03-11 04:13 UTC, VaninaY commented on cartpole_en.rst
> +.. code::python
.. code:: python

2022-03-11 04:13 UTC, VaninaY commented on cartpole_en.rst
> +- \``Pole Angle``\: The angle of the pole, in the range \``[-24 deg, 24 deg]``\.
- \ ``Pole Angle`` \: The angle of the pole, in the range \ ``[-24 deg, 24 deg]`` \.

2022-03-11 04:13 UTC, VaninaY commented on cartpole_en.rst
> +- \``Pole Angular Velocity``\: The angular velocity of the pole, in the range \``[-inf, inf]``\.
- \ ``Pole Angular Velocity`` \: The angular velocity of the pole, in the range \ ``[-inf, inf]`` \.

2022-03-11 04:13 UTC, VaninaY commented on cartpole_en.rst
> +.. code::python
.. code:: python

2022-03-30 10:59 UTC, PaParaZz1 requested changes

2022-03-30 10:59 UTC, PaParaZz1 commented on Gym_en.rst
> +gym_hybrid_en.rst
rename this file to `gym_hybrid_en.rst`, and rename the head to `gym hybrid`

2022-03-30 10:59 UTC, PaParaZz1 commented on Gym_en.rst
> +=========
it should be longer than the head

2022-03-30 10:59 UTC, PaParaZz1 commented on Gym_en.rst
> +~~~~~~~~~~~~~~~~~~~
move these two files to `source/env_tutorial`

2022-03-30 10:59 UTC, PaParaZz1 commented on Gym_en.rst
> +- Gym-hybrid `source code <https://github.com/thomashirtz/gym-hybrid>`__
No need for capitalization here

2022-05-11 08:16 UTC, PaParaZz1 commented
This PR has been integrated in #135

2022-05-11 08:16 UTC, closed without merging