chuming add mbpo
opendilab/DI-engine-docs pull request #82
Opened 2022-01-26 07:54 UTC by Will-Nie

chuming adds mbpo algo benchmark doc

2022-02-10 09:34 UTC, PaParaZz1 requested changes

2022-02-12 15:44 UTC, jiaruonan commented on source/hands_on/mbpo.rst
> +Model-based policy optimization (MBPO) was first proposed in `When to Trust Your Model: Model-Based Policy Optimization <https://arxiv.org/abs/1906.08253>`_. MBPO utilizes short model-generated rollo
** trains an ensemble of [probabilistic] models **

2022-02-12 15:44 UTC, jiaruonan commented on source/hands_on/mbpo.rst
> +   L(w)=\mathbb{E}\left[log( f^w(\boldsymbol{s}_{t+1}|\boldsymbol{s}_t,\boldsymbol{a}_t))\right]
建议模型符号f和参数w改为p和θ，与下面伪代码中的模型表示相对应。

2022-02-12 15:44 UTC, jiaruonan commented on source/hands_on/mbpo.rst
> +
补充一些related work: Extensions ?

2022-02-12 15:44 UTC, jiaruonan commented on source/hands_on/mbpo.rst
> +4. MBPOuses **model-eensemble**.
补充一点：5. The model usage of MBPO is to do k-length rollouts from replay buffer.

2022-02-16 07:58 UTC, lichuming commented on source/hands_on/mbpo.rst
> +
Trust the Model When It Is Confident:
Masked Model-based Actor-Critic
https://proceedings.neurips.cc/paper/2020/file/77133be2e96a577bd4794928976d2ae2-Paper.pdf
加上这篇作为extension

2022-03-30 04:44 UTC, merged