add rainbow benchmark results and polish the doc
opendilab/DI-engine-docs pull request #85
Opened 2022-02-14 04:23 UTC by song2181

2022-02-14 09:59 UTC, mugicaxu commented on source/hands_on/rainbow.rst
> -Double Q-learning maintains a target q network, which is periodically updated with the current q network. Double Q-learning decouples the over-estimation of q-value by selects action with the current
maintain

2022-02-14 09:59 UTC, mugicaxu commented on source/hands_on/rainbow.rst
> +Double Q-learning maintains a target q network, which is periodically updated with the current q network. Double Q-learning addresses the overestimation of q-value by decoupling. It selects action wi
maintain

2022-02-14 13:20 UTC, PaParaZz1 requested changes

2022-02-14 13:20 UTC, PaParaZz1 commented on source/hands_on/rainbow.rst
reference中给出所有rainbow的trick对应的paper吧

2022-02-14 13:20 UTC, PaParaZz1 commented on source/hands_on/rainbow.rst
noisy net这里下面的一些数学符号写规范一点吧，比如正态分布

2022-02-14 13:20 UTC, PaParaZz1 commented on source/hands_on/rainbow.rst
> +>>>>>>>>>>>>>>>>>
参照DQN那边更新下Double DQN的说明吧，target network是DQN就有的，Double DQN是target action通过current network来取，target value通过target network来取

2022-02-14 13:20 UTC, PaParaZz1 commented on source/hands_on/rainbow.rst
> +Rainbow was proposed in `Rainbow: Combining Improvements in Deep Reinforcement Learning <https://arxiv.org/abs/1710.02298>`_. It combines many independent improvements to DQN, including: target netwo
这里把`target network(double DQN)`改为`Double DQN`

2022-02-14 13:20 UTC, PaParaZz1 commented on source/hands_on/rainbow.rst
>  -----------------------------
下面的代码段把缩进弄对，4个空格

2022-03-30 04:47 UTC, PaParaZz1 approved these changes

2022-03-30 04:47 UTC, merged